import { buildOperationalHealthReportFromOfficeQueue } from "@/shared/types/operational-health-report";
import type { DashboardData } from "@/shared/types/dashboard";
import type { OfficeReviewQueueReport } from "@/shared/types/office-review-queue";
import { buildReportSectionMeta } from "@/shared/types/reports";

const DEMO_NOW = "2026-06-23T14:00:00.000Z";
const DEMO_TODAY = "2026-06-23";

const FOUNDER_ACCESS: DashboardData["access"] = {
  canViewBilling: true,
  canViewOperationalReports: true,
  canViewAllJobs: true,
  canViewAssignedJobs: true,
  canViewCompanyExpenses: true,
  canViewTechnicianRoster: true,
  canManageCustomers: true,
  canManageTeamMembers: true,
};

const REPORT_META = buildReportSectionMeta({
  dateRange: "30d",
  dateBounds: null,
  limitations: ["Design Lab static demo fixture only."],
});

const RESOLUTION_TREND = {
  resolvedThisWeek: 4,
  resolvedLastWeek: 3,
  weekOverWeekDelta: 1,
  rollingSevenDayAverage: 3.5,
  direction: "improving" as const,
  headline: "Cleanup pace improving",
  detail: "4 office queue items resolved this week.",
  limitations: [] as string[],
};

function buildDemoOfficeReviewQueue(): OfficeReviewQueueReport {
  const items: OfficeReviewQueueReport["summary"]["items"] = [
    {
      jobId: "job-demo-1001",
      jobNumber: "JOB-DEMO-1001",
      customerName: "Miller Residence",
      kind: "completed_work_review",
      severity: "critical",
      group: "critical",
      daysAging: 2,
      agingBucket: "fresh",
      agingLabel: "2 days old",
      severityEscalated: false,
      blockerCount: 1,
      reviewReasons: ["no_active_invoice"],
      lastActivityAt: DEMO_NOW,
      assignedTechnician: "Alex Rivera",
      jobStatus: "completed",
      detail: "Completed work needs office review before invoicing.",
      readinessScore: 50,
      readinessLabel: "Needs review",
      readinessColor: "amber",
      readinessExplanation: "Invoice not yet created for completed work.",
    },
    {
      jobId: "job-demo-1004",
      jobNumber: "JOB-DEMO-1004",
      customerName: "Clearfield Property Group",
      kind: "awaiting_invoicing",
      severity: "warning",
      group: "needs_attention",
      daysAging: 4,
      agingBucket: "aging",
      agingLabel: "4 days old",
      severityEscalated: false,
      blockerCount: 0,
      reviewReasons: [],
      lastActivityAt: DEMO_NOW,
      assignedTechnician: "Jordan Lee",
      jobStatus: "completed",
      detail: "Completed yesterday — ready for invoice draft.",
      readinessScore: 75,
      readinessLabel: "Ready to bill",
      readinessColor: "emerald",
      readinessExplanation: "Work complete and approved for billing.",
    },
  ];

  const queue: OfficeReviewQueueReport = {
    summary: {
      totalCount: items.length,
      criticalCount: 1,
      needsAttentionCount: 1,
      agingCount: 0,
      agingBucketCounts: { fresh: 1, aging: 1, overdue: 0 },
      resolvedThisWeek: 4,
      resolutionTrend: RESOLUTION_TREND,
      groups: {
        critical: [items[0]],
        needs_attention: [items[1]],
        aging: [],
      },
      items,
    },
    meta: REPORT_META,
  };

  return queue;
}

const OFFICE_REVIEW_QUEUE = buildDemoOfficeReviewQueue();

export const DESIGN_LAB_DASHBOARD_FIXTURE: DashboardData = {
  access: FOUNDER_ACCESS,
  analytics: {
    todayCollectedRevenue: 2840,
    todayPaymentCount: 3,
    openJobs: 18,
    pendingExpenseCount: 2,
    activeLaborEntries: 4,
    reviewIssuesResolvedThisWeek: 4,
  },
  operations: {
    scheduledToday: 8,
    dispatched: 2,
    inProgress: 3,
    completedToday: 2,
    unassignedToday: 2,
    totalJobsToday: 8,
    overloadedTechnicianCount: 1,
    todayJobs: [
      {
        id: "job-demo-2001",
        customerId: "cust-demo-1",
        jobNumber: "JOB-DEMO-2001",
        customerName: "Miller Residence",
        serviceAddress: "412 Oak Lane",
        city: "Layton",
        state: "UT",
        zip: "84041",
        jobType: "AC diagnostic",
        technicianId: "tech-demo-1",
        scheduledDate: `${DEMO_TODAY}T09:00:00.000Z`,
        status: "in_progress",
        priority: "high",
      },
      {
        id: "job-demo-2002",
        customerId: "cust-demo-2",
        jobNumber: "JOB-DEMO-2002",
        customerName: "Anderson Home",
        serviceAddress: "88 Canyon View Dr",
        city: "Ogden",
        state: "UT",
        zip: "84403",
        jobType: "Furnace tune-up",
        technicianId: "tech-demo-2",
        scheduledDate: `${DEMO_TODAY}T10:30:00.000Z`,
        status: "dispatched",
        priority: "normal",
      },
      {
        id: "job-demo-2003",
        customerId: "cust-demo-3",
        jobNumber: "JOB-DEMO-2003",
        customerName: "Clearfield Property Group",
        serviceAddress: "1200 W Center St",
        city: "Clearfield",
        state: "UT",
        zip: "84015",
        jobType: "Maintenance agreement",
        technicianId: "tech-demo-3",
        scheduledDate: `${DEMO_TODAY}T13:00:00.000Z`,
        status: "scheduled",
        priority: "normal",
      },
      {
        id: "job-demo-2004",
        customerId: "cust-demo-4",
        jobNumber: "JOB-DEMO-2004",
        customerName: "Roy Residence",
        serviceAddress: "55 Maple Ave",
        city: "Roy",
        state: "UT",
        zip: "84067",
        jobType: "No-cool callback",
        scheduledDate: `${DEMO_TODAY}T15:00:00.000Z`,
        status: "scheduled",
        priority: "urgent",
      },
    ],
    unassignedJobs: [
      {
        id: "job-demo-2004",
        customerId: "cust-demo-4",
        jobNumber: "JOB-DEMO-2004",
        customerName: "Roy Residence",
        serviceAddress: "55 Maple Ave",
        city: "Roy",
        state: "UT",
        zip: "84067",
        jobType: "No-cool callback",
        scheduledDate: `${DEMO_TODAY}T15:00:00.000Z`,
        status: "scheduled",
        priority: "urgent",
      },
      {
        id: "job-demo-2005",
        customerId: "cust-demo-5",
        jobNumber: "JOB-DEMO-2005",
        customerName: "Bountiful Home",
        serviceAddress: "901 Orchard Way",
        city: "Bountiful",
        state: "UT",
        zip: "84010",
        jobType: "Estimate follow-up",
        scheduledDate: `${DEMO_TODAY}T16:30:00.000Z`,
        status: "scheduled",
        priority: "normal",
      },
    ],
  },
  technicians: [
    {
      id: "tech-demo-1",
      name: "Alex Rivera",
      initials: "AR",
      timeState: "working_job",
      currentJobId: "job-demo-2001",
      currentJobNumber: "JOB-DEMO-2001",
    },
    {
      id: "tech-demo-2",
      name: "Jordan Lee",
      initials: "JL",
      timeState: "working_job",
      currentJobId: "job-demo-2002",
      currentJobNumber: "JOB-DEMO-2002",
    },
    {
      id: "tech-demo-3",
      name: "Sam Patel",
      initials: "SP",
      timeState: "clocked_in",
    },
  ],
  assignableTechnicians: [
    {
      id: "tech-demo-1",
      name: "Alex Rivera",
      role: "Technician",
      initials: "AR",
      status: "on_job",
      specialty: "HVAC",
      specialties: ["HVAC"],
      phone: "555-0101",
    },
    {
      id: "tech-demo-2",
      name: "Jordan Lee",
      role: "Technician",
      initials: "JL",
      status: "on_job",
      specialty: "HVAC",
      specialties: ["HVAC"],
      phone: "555-0102",
    },
    {
      id: "tech-demo-3",
      name: "Sam Patel",
      role: "Technician",
      initials: "SP",
      status: "available",
      specialty: "HVAC",
      specialties: ["HVAC"],
      phone: "555-0103",
    },
  ],
  money: {
    unpaidCount: 6,
    unpaidTotal: 12480,
    overdueCount: 2,
    overdueTotal: 4280,
    paymentsTodayCount: 3,
    paymentsTodayTotal: 2840,
    recentPayments: [
      {
        id: "pay-demo-1",
        invoiceId: "inv-demo-1",
        invoiceNumber: "INV-DEMO-1042",
        customerName: "Anderson Home",
        amount: 980,
        paymentDate: DEMO_TODAY,
        createdAt: DEMO_NOW,
      },
    ],
    approvedEstimates: [],
    overdueInvoices: [
      {
        id: "inv-demo-2",
        invoiceNumber: "INV-DEMO-1031",
        customerName: "Miller Residence",
        balanceDue: 2480,
        dueDate: "2026-06-10",
        status: "overdue",
      },
      {
        id: "inv-demo-3",
        invoiceNumber: "INV-DEMO-1028",
        customerName: "Clearfield Property Group",
        balanceDue: 1800,
        dueDate: "2026-06-12",
        status: "overdue",
      },
    ],
    unpaidInvoiceFollowUpCount: 0,
    unpaidInvoicesNeedingFollowUp: [],
    unpaidInvoiceFollowUpThresholdDays: 7,
    unsentInvoiceCount: 2,
    unsentInvoices: [
      {
        id: "inv-demo-4",
        invoiceNumber: "INV-DEMO-1045",
        customerName: "Roy Residence",
        total: 620,
        status: "draft",
      },
      {
        id: "inv-demo-5",
        invoiceNumber: "INV-DEMO-1046",
        customerName: "Bountiful Home",
        total: 1140,
        status: "draft",
      },
    ],
    unsentEstimateCount: 1,
    unsentEstimates: [
      {
        id: "est-demo-1",
        estimateNumber: "EST-DEMO-301",
        customerName: "Miller Residence",
        total: 8200,
        status: "draft",
      },
    ],
    staleSentEstimateCount: 1,
    staleSentEstimates: [
      {
        id: "est-demo-2",
        estimateNumber: "EST-DEMO-298",
        customerName: "Clearfield Property Group",
        total: 15600,
        status: "sent",
        sentAt: "2026-06-12T10:00:00.000Z",
        daysSinceSent: 11,
      },
    ],
    staleSentEstimateThresholdDays: 7,
  },
  expenses: {
    submittedCount: 2,
    submittedTotal: 186,
    rejectedCount: 0,
    recentReceipts: [],
    pendingExpenses: [],
  },
  notifications: {
    unreadCount: 3,
    recent: [
      {
        id: "notif-demo-1",
        companyId: "company-demo",
        type: "draft_invoice_ready",
        title: "Invoice overdue",
        message: "INV-DEMO-1031 is 13 days past due.",
        createdAt: DEMO_NOW,
        metadata: {},
      },
    ],
  },
  officeReviewQueue: OFFICE_REVIEW_QUEUE,
  stalledJobs: {
    stalledCount: 2,
    inactivityThresholdDays: 5,
    stalledJobs: [
      {
        jobId: "job-demo-3001",
        jobNumber: "JOB-DEMO-3001",
        customerName: "Anderson Home",
        status: "in_progress",
        assignedTechnician: "Jordan Lee",
        lastActivityAt: "2026-06-15T16:00:00.000Z",
        daysSinceActivity: 8,
      },
      {
        jobId: "job-demo-3002",
        jobNumber: "JOB-DEMO-3002",
        customerName: "Bountiful Home",
        status: "scheduled",
        lastActivityAt: "2026-06-14T11:00:00.000Z",
        daysSinceActivity: 9,
      },
    ],
  },
  completedWorkAwaitingInvoicing: {
    count: 3,
    jobs: [
      {
        jobId: "job-demo-1004",
        jobNumber: "JOB-DEMO-1004",
        customerName: "Clearfield Property Group",
        completedAt: "2026-06-22T17:30:00.000Z",
        assignedTechnician: "Jordan Lee",
        approvedEstimateAmount: 2400,
        collectedRevenue: 0,
        daysSinceCompletion: 1,
      },
      {
        jobId: "job-demo-1005",
        jobNumber: "JOB-DEMO-1005",
        customerName: "Roy Residence",
        completedAt: "2026-06-21T14:00:00.000Z",
        assignedTechnician: "Alex Rivera",
        approvedEstimateAmount: 980,
        collectedRevenue: 0,
        daysSinceCompletion: 2,
      },
      {
        jobId: "job-demo-1006",
        jobNumber: "JOB-DEMO-1006",
        customerName: "Miller Residence",
        completedAt: "2026-06-20T12:00:00.000Z",
        assignedTechnician: "Sam Patel",
        approvedEstimateAmount: 1560,
        collectedRevenue: 0,
        daysSinceCompletion: 3,
      },
    ],
  },
  completedWorkReview: {
    count: 2,
    resolvedThisWeek: 4,
    jobs: [
      {
        jobId: "job-demo-1001",
        jobNumber: "JOB-DEMO-1001",
        customerName: "Miller Residence",
        completedAt: "2026-06-21T16:00:00.000Z",
        assignedTechnician: "Alex Rivera",
        daysSinceCompletion: 2,
        reviewReasons: ["no_active_invoice"],
        severity: "critical",
        invoiceStatus: {
          activeInvoiceCount: 0,
          statuses: [],
          latestStatus: null,
        },
        profitabilityWarningCount: 0,
      },
      {
        jobId: "job-demo-1002",
        jobNumber: "JOB-DEMO-1002",
        customerName: "Anderson Home",
        completedAt: "2026-06-20T11:00:00.000Z",
        assignedTechnician: "Jordan Lee",
        daysSinceCompletion: 3,
        reviewReasons: ["open_labor_entries"],
        severity: "warning",
        invoiceStatus: {
          activeInvoiceCount: 1,
          statuses: ["draft"],
          latestStatus: "draft",
        },
        profitabilityWarningCount: 1,
      },
    ],
  },
  acceptedEstimatesNeedingScheduling: {
    count: 1,
    estimates: [
      {
        id: "est-demo-approved-1",
        estimateNumber: "EST-DEMO-301",
        customerName: "Roy Residence",
        total: 1840,
        approvedAt: "2026-06-23T14:00:00.000Z",
        jobId: "job-demo-1010",
        jobNumber: "JOB-DEMO-1010",
        openHref: "/jobs/job-demo-1010",
      },
    ],
  },
  leadFollowUp: {
    count: 2,
    leads: [
      {
        id: "lead-demo-1",
        firstName: "Chris",
        lastName: "Nguyen",
        phone: "555-0201",
        email: "chris@example.com",
        nextFollowUpAt: "2026-06-23T09:00:00.000Z",
        status: "contacted",
      },
      {
        id: "lead-demo-2",
        firstName: "Taylor",
        lastName: "Brooks",
        companyName: "Brooks Property Mgmt",
        phone: "555-0202",
        email: "taylor@example.com",
        nextFollowUpAt: "2026-06-22T14:00:00.000Z",
        status: "contacted",
      },
    ],
  },
  newLeadsNeedingContact: {
    count: 1,
    leads: [
      {
        id: "lead-demo-new-1",
        firstName: "Jordan",
        lastName: "Lee",
        phone: "555-0203",
        email: "jordan@example.com",
        status: "new",
        createdAt: "2026-06-24T08:00:00.000Z",
        sourceLabel: "Website",
        openHref: "/leads?selected=lead-demo-new-1",
      },
    ],
  },
  leadsReadyForEstimate: {
    count: 1,
    leads: [
      {
        id: "lead-demo-qualified-1",
        firstName: "Sam",
        lastName: "Rivera",
        phone: "555-0204",
        email: "sam@example.com",
        status: "contacted",
        createdAt: "2026-06-20T10:00:00.000Z",
        sourceLabel: "Referral",
        openHref: "/leads?selected=lead-demo-qualified-1",
      },
    ],
  },
  leadPipelineSummary: {
    totalLeads: 14,
    followUpsDue: 2,
    wonLeads: 3,
    lostLeads: 1,
    hasLeads: true,
  },
  operationalInsights: {
    generatedAt: DEMO_NOW,
    sections: {
      revenue: {
        collectedRevenue: 42800,
        outstandingRevenue: 12480,
        todayCollectedRevenue: 2840,
        todayPaymentCount: 3,
      },
      openJobs: { count: 18 },
      stalledJobs: {
        count: 2,
        inactivityThresholdDays: 5,
        stalledJobs: [],
      },
      pendingExpenses: { count: 2, totalAmount: 186 },
      activeTechnicians: { activeLaborEntries: 4, technicianCount: 3 },
      completedAwaitingInvoicing: { count: 3, jobs: [] },
      completedWorkReview: {
        count: 2,
        jobs: [],
        resolvedThisWeek: 4,
        resolutionTrend: RESOLUTION_TREND,
      },
      profitabilityWarnings: {
        jobsWithWarnings: 1,
        materialCostExceedsCollectedCount: 0,
      },
    },
    highlights: [
      {
        id: "highlight-demo-1",
        severity: "warning",
        message: "2 overdue invoices need collection follow-up.",
        category: "revenue",
        count: 2,
      },
      {
        id: "highlight-demo-2",
        severity: "info",
        message: "3 completed jobs are awaiting invoicing.",
        category: "invoicing",
        count: 3,
      },
    ],
    limitations: [],
  },
  operationalHealth: buildOperationalHealthReportFromOfficeQueue(OFFICE_REVIEW_QUEUE, {
    jobsWithWarnings: 1,
    materialCostExceedsCollectedCount: 0,
  }),
  recentActivity: [
    {
      id: "activity-demo-1",
      source: "job",
      eventType: "work_completed",
      rawEventType: "work_completed",
      metadata: {
        job_number: "JOB-DEMO-1004",
        customer_name: "Clearfield Property Group",
      },
      createdAt: "2026-06-22T17:30:00.000Z",
      jobId: "job-demo-1004",
    },
    {
      id: "activity-demo-2",
      source: "invoice",
      eventType: "invoice_sent",
      rawEventType: "invoice_sent",
      metadata: {
        invoice_number: "INV-DEMO-1042",
        customer_name: "Anderson Home",
      },
      createdAt: "2026-06-23T08:15:00.000Z",
      invoiceId: "inv-demo-1",
    },
    {
      id: "activity-demo-3",
      source: "estimate",
      eventType: "estimate_sent",
      rawEventType: "estimate_sent",
      metadata: {
        estimate_number: "EST-DEMO-298",
        customer_name: "Clearfield Property Group",
      },
      createdAt: "2026-06-12T10:00:00.000Z",
      estimateId: "est-demo-2",
    },
  ],
};
