export {
  AltairTable,
  AltairTableHeader,
  AltairTableBody,
  AltairTableRow,
  AltairTableHead,
  AltairTableCell,
  AltairTablePrimaryCell,
  AltairTableSecondaryText,
  type AltairTableProps,
  type AltairTableHeaderProps,
  type AltairTableBodyProps,
  type AltairTableRowProps,
  type AltairTableHeadProps,
  type AltairTableCellProps,
  type AltairTableCellAlign,
  type AltairTablePrimaryCellProps,
  type AltairTableSecondaryTextProps,
} from "./AltairTable";
