import {
  ELECTRICAL_DEMO_CUSTOMERS,
  ELECTRICAL_DEMO_EQUIPMENT,
  ELECTRICAL_DEMO_JOBS,
  ELECTRICAL_DEMO_LEADS,
  ELECTRICAL_DEMO_SERVICE_ITEMS,
} from "@/lib/database/services/demo-data-seed-definitions-electrical";
import type {
  EstimateSeed,
  InvoiceSeed,
  MaterialSeed,
  NotificationSeed,
} from "@/lib/database/services/demo-data-seed-definitions";

export const ELECTRICAL_DEMO_MATERIALS: MaterialSeed[] = [
  {
    customerKey: "alex",
    jobKey: "completedAlexPanel",
    serviceItemKey: "panel-inspection",
    name: "Panel inspection checklist",
    quantity: 1,
    unitCost: 5,
    unitPrice: 25,
  },
  {
    customerKey: "alex",
    jobKey: "completedAlexEv",
    serviceItemKey: "ev-charger",
    name: "40A EV charger breaker",
    quantity: 1,
    unitCost: 35,
    unitPrice: 85,
  },
  {
    customerKey: "harbor",
    jobKey: "completedHarborGfci",
    serviceItemKey: "gfci-outlet",
    name: "20A GFCI duplex outlet",
    quantity: 2,
    unitCost: 18,
    unitPrice: 42,
  },
  {
    customerKey: "summit",
    jobKey: "completedSummitDedicated",
    serviceItemKey: "dedicated-circuit",
    name: "30A dryer outlet — 4-wire",
    quantity: 1,
    unitCost: 22,
    unitPrice: 65,
  },
  {
    customerKey: "blake",
    jobKey: "completedBlakeBreaker",
    serviceItemKey: "breaker-troubleshoot",
    name: "20A AFCI breaker",
    quantity: 1,
    unitCost: 28,
    unitPrice: 75,
  },
  {
    customerKey: "morgan",
    jobKey: "completedMorganGfci",
    serviceItemKey: "gfci-outlet",
    name: "15A GFCI outlet — tamper resistant",
    quantity: 1,
    unitCost: 16,
    unitPrice: 38,
  },
  {
    customerKey: "cedar",
    jobKey: "completedCedarSmoke",
    serviceItemKey: "smoke-detector",
    name: "Hardwired smoke detector",
    quantity: 4,
    unitCost: 32,
    unitPrice: 58,
  },
  {
    customerKey: "corner",
    jobKey: "completedCornerDedicated",
    serviceItemKey: "dedicated-circuit",
    name: "50A range outlet",
    quantity: 1,
    unitCost: 45,
    unitPrice: 95,
  },
  {
    customerKey: "storefront",
    jobKey: "completedStorefrontFixture",
    serviceItemKey: "light-fixture",
    name: "LED track light heads — 4 pack",
    quantity: 1,
    unitCost: 68,
    unitPrice: 145,
  },
  {
    customerKey: "market",
    jobKey: "completedMarketSubpanel",
    serviceItemKey: "subpanel",
    name: "60A subpanel kit",
    quantity: 1,
    unitCost: 185,
    unitPrice: 420,
  },
  {
    customerKey: "clinic",
    jobKey: "completedClinicEmergency",
    serviceItemKey: "light-fixture",
    name: "LED emergency exit sign",
    quantity: 2,
    unitCost: 55,
    unitPrice: 120,
  },
  {
    customerKey: "workspace",
    jobKey: "completedWorkspaceSubpanel",
    serviceItemKey: "subpanel",
    name: "100A subpanel upgrade kit",
    quantity: 1,
    unitCost: 240,
    unitPrice: 550,
  },
];

export const ELECTRICAL_DEMO_ESTIMATES: EstimateSeed[] = [
  {
    key: "draftPanel",
    customerKey: "reese",
    jobKey: "panelQuoteTomorrow",
    estimateNumber: "EST-DEMO-2001",
    status: "draft",
    subtotal: 3800,
    validUntilDaysFromNow: 21,
    notes: "Draft panel upgrade quote — finalize after load calculation review.",
    createdDaysAgo: 4,
    lineItems: [
      {
        serviceItemKey: "panel-upgrade",
        name: "Panel Upgrade",
        description: "200A panel replacement with new breakers and grounding.",
        quantity: 1,
        unitPrice: 3800,
      },
    ],
  },
  {
    key: "sentEvCharger",
    customerKey: "alex",
    estimateNumber: "EST-DEMO-2002",
    status: "sent",
    subtotal: 1850,
    validUntilDaysFromNow: 10,
    notes: "EV charger installation sent — awaiting homeowner approval.",
    createdDaysAgo: 12,
    lineItems: [
      {
        serviceItemKey: "ev-charger",
        name: "EV Charger Installation",
        description: "Level 2 charger with dedicated 50A circuit.",
        quantity: 1,
        unitPrice: 1850,
      },
    ],
  },
  {
    key: "approvedSubpanel",
    customerKey: "harbor",
    jobKey: "completedHarborGfci",
    estimateNumber: "EST-DEMO-2003",
    status: "approved",
    subtotal: 2200,
    validUntilDaysFromNow: 30,
    notes: "Approved subpanel expansion for Suite 400 — install scheduled.",
    createdDaysAgo: 35,
    lineItems: [
      {
        serviceItemKey: "subpanel",
        name: "Subpanel Installation",
        description: "Expand subpanel capacity for new office circuits.",
        quantity: 1,
        unitPrice: 2200,
      },
    ],
  },
  {
    key: "draftRecessed",
    customerKey: "storefront",
    estimateNumber: "EST-DEMO-2004",
    status: "approved",
    subtotal: 975,
    validUntilDaysFromNow: 14,
    notes: "Approved recessed lighting in display area — scheduled with fixture visit.",
    createdDaysAgo: 2,
    lineItems: [
      {
        serviceItemKey: "recessed-lighting",
        name: "Recessed Lighting Installation",
        description: "Install three recessed cans in retail display ceiling.",
        quantity: 3,
        unitPrice: 325,
      },
    ],
  },
  {
    key: "sentDedicated",
    customerKey: "corner",
    estimateNumber: "EST-DEMO-2005",
    status: "approved",
    subtotal: 1475,
    validUntilDaysFromNow: 21,
    notes: "Approved dedicated oven circuit — parts ordered, install window confirmed.",
    createdDaysAgo: 5,
    lineItems: [
      {
        serviceItemKey: "dedicated-circuit",
        name: "Dedicated Circuit Installation",
        description: "50A circuit for commercial oven.",
        quantity: 1,
        unitPrice: 425,
      },
      {
        serviceItemKey: "labor",
        name: "Standard Labor Rate",
        description: "Additional labor for conduit run through kitchen.",
        quantity: 10,
        unitPrice: 105,
      },
    ],
  },
  {
    key: "sentSurge",
    customerKey: "clinic",
    estimateNumber: "EST-DEMO-2006",
    status: "approved",
    subtotal: 485,
    validUntilDaysFromNow: 30,
    notes: "Approved whole-home surge protector for medical office panel.",
    createdDaysAgo: 4,
    lineItems: [
      {
        serviceItemKey: "whole-home-surge",
        name: "Whole-Home Surge Protector",
        description: "Panel-mounted surge protection for sensitive equipment.",
        quantity: 1,
        unitPrice: 485,
      },
    ],
  },
  {
    key: "approvedInspection",
    customerKey: "summit",
    estimateNumber: "EST-DEMO-2007",
    status: "approved",
    subtotal: 398,
    validUntilDaysFromNow: 45,
    notes: "Approved annual safety inspection contract for two buildings.",
    createdDaysAgo: 40,
    lineItems: [
      {
        serviceItemKey: "safety-inspection",
        name: "Electrical Safety Inspection",
        description: "Rental turnover safety walkthrough per building.",
        quantity: 2,
        unitPrice: 199,
      },
    ],
  },
  {
    key: "approvedSubpanelCedar",
    customerKey: "cedar",
    jobKey: "completedCedarSmoke",
    estimateNumber: "EST-DEMO-2008",
    status: "approved",
    subtotal: 2200,
    validUntilDaysFromNow: 60,
    notes: "Approved clubhouse subpanel upgrade for expanded lighting.",
    createdDaysAgo: 42,
    lineItems: [
      {
        serviceItemKey: "subpanel",
        name: "Subpanel Installation",
        description: "Upgrade clubhouse subpanel for new common-area circuits.",
        quantity: 1,
        unitPrice: 2200,
      },
    ],
  },
  {
    key: "declinedGenerator",
    customerKey: "blake",
    estimateNumber: "EST-DEMO-2009",
    status: "declined",
    subtotal: 650,
    validUntilDaysFromNow: 14,
    notes: "Generator interlock kit declined — customer postponed backup power project.",
    createdDaysAgo: 4,
    lineItems: [
      {
        serviceItemKey: "generator-interlock",
        name: "Generator Interlock Kit",
        description: "Manual transfer interlock for portable generator backup.",
        quantity: 1,
        unitPrice: 650,
      },
    ],
  },
  {
    key: "approvedMaple",
    customerKey: "maple",
    estimateNumber: "EST-DEMO-2010",
    status: "approved",
    subtotal: 3800,
    validUntilDaysFromNow: 60,
    notes: "Approved building main panel upgrade — phased install over two weekends.",
    createdDaysAgo: 45,
    lineItems: [
      {
        serviceItemKey: "panel-upgrade",
        name: "Panel Upgrade",
        description: "Replace aging 100A panel with 200A load center.",
        quantity: 1,
        unitPrice: 3800,
      },
    ],
  },
];

export const ELECTRICAL_DEMO_INVOICES: InvoiceSeed[] = [
  {
    key: "paidDiag",
    customerKey: "summit",
    jobKey: "completedSummitInspection",
    invoiceNumber: "INV-DEMO-3001",
    status: "paid",
    subtotal: 199,
    amountPaid: 0,
    issueDaysAgo: 24,
    dueDaysFromNow: 6,
    paidDaysAgo: 20,
    notes: "Safety inspection — paid in full.",
    lineItems: [
      {
        serviceItemKey: "safety-inspection",
        name: "Electrical Safety Inspection",
        description: "Rental turnover safety walkthrough.",
        quantity: 1,
        unitPrice: 199,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 20,
        reference: "DEMO-PAY-3001",
        notes: "Paid in full — check.",
        paymentMethod: "check",
      },
    ],
  },
  {
    key: "partialHarbor",
    customerKey: "harbor",
    jobKey: "completedHarborGfci",
    invoiceNumber: "INV-DEMO-3002",
    status: "partially_paid",
    subtotal: 330,
    amountPaid: 165,
    issueDaysAgo: 38,
    dueDaysFromNow: 12,
    notes: "GFCI replacement — deposit received, final balance on net-30 terms.",
    lineItems: [
      {
        serviceItemKey: "gfci-outlet",
        name: "GFCI Outlet Replacement",
        description: "Replace two failed GFCI outlets in office suite.",
        quantity: 2,
        unitPrice: 165,
      },
    ],
    payments: [
      {
        amount: 100,
        paymentDaysAgo: 35,
        reference: "DEMO-PAY-3002A",
        notes: "Initial deposit.",
        paymentMethod: "check",
      },
      {
        amount: 65,
        paymentDaysAgo: 8,
        reference: "DEMO-PAY-3002B",
        notes: "Second installment.",
        paymentMethod: "card",
      },
    ],
  },
  {
    key: "paidPanel",
    customerKey: "alex",
    jobKey: "completedAlexPanel",
    invoiceNumber: "INV-DEMO-3003",
    status: "paid",
    subtotal: 149,
    amountPaid: 0,
    issueDaysAgo: 20,
    dueDaysFromNow: 6,
    paidDaysAgo: 16,
    notes: "Panel inspection completed — paid in full.",
    lineItems: [
      {
        serviceItemKey: "panel-inspection",
        name: "Panel Inspection",
        description: "Annual panel inspection service.",
        quantity: 1,
        unitPrice: 149,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 16,
        reference: "DEMO-PAY-3003",
        notes: "Paid in full — card on file.",
        paymentMethod: "card",
      },
    ],
  },
  {
    key: "paidHistoricalEv",
    customerKey: "alex",
    jobKey: "completedAlexEv",
    invoiceNumber: "INV-DEMO-3004",
    status: "paid",
    subtotal: 1850,
    amountPaid: 0,
    issueDaysAgo: 54,
    dueDaysFromNow: -24,
    paidDaysAgo: 50,
    notes: "EV charger installation — paid in full.",
    lineItems: [
      {
        serviceItemKey: "ev-charger",
        name: "EV Charger Installation",
        description: "Level 2 charger with dedicated circuit.",
        quantity: 1,
        unitPrice: 1850,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 50,
        reference: "DEMO-PAY-3004",
        notes: "Historical paid invoice for revenue reporting.",
        paymentMethod: "cash",
      },
    ],
  },
  {
    key: "paidBlake",
    customerKey: "blake",
    jobKey: "completedBlakeBreaker",
    invoiceNumber: "INV-DEMO-3005",
    status: "paid",
    subtotal: 159,
    amountPaid: 0,
    issueDaysAgo: 10,
    dueDaysFromNow: 20,
    paidDaysAgo: 7,
    notes: "Breaker troubleshooting — paid via card on-site.",
    lineItems: [
      {
        serviceItemKey: "breaker-troubleshoot",
        name: "Breaker Troubleshooting",
        description: "Diagnose and repair tripping workshop breaker.",
        quantity: 1,
        unitPrice: 159,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 7,
        reference: "DEMO-PAY-3005",
        notes: "Paid in full — card on-site.",
        paymentMethod: "card",
      },
    ],
  },
  {
    key: "partialCorner",
    customerKey: "corner",
    jobKey: "completedCornerDedicated",
    invoiceNumber: "INV-DEMO-3006",
    status: "partially_paid",
    subtotal: 425,
    amountPaid: 250,
    issueDaysAgo: 12,
    dueDaysFromNow: 18,
    notes: "Dedicated circuit install — deposit received, final balance due on net-30 terms.",
    lineItems: [
      {
        serviceItemKey: "dedicated-circuit",
        name: "Dedicated Circuit Installation",
        description: "50A circuit for commercial oven.",
        quantity: 1,
        unitPrice: 425,
      },
    ],
    payments: [
      {
        amount: 250,
        paymentDaysAgo: 42,
        reference: "DEMO-PAY-3006",
        notes: "Partial payment — restaurant manager check.",
        paymentMethod: "check",
      },
    ],
  },
  {
    key: "paidMarket",
    customerKey: "market",
    jobKey: "completedMarketSubpanel",
    invoiceNumber: "INV-DEMO-3007",
    status: "paid",
    subtotal: 2200,
    amountPaid: 0,
    issueDaysAgo: 28,
    dueDaysFromNow: 2,
    paidDaysAgo: 24,
    notes: "Subpanel installation — paid via ACH.",
    lineItems: [
      {
        serviceItemKey: "subpanel",
        name: "Subpanel Installation",
        description: "60A subpanel for expanded studio circuits.",
        quantity: 1,
        unitPrice: 2200,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 24,
        reference: "DEMO-PAY-3007",
        notes: "Paid in full — ACH transfer.",
        paymentMethod: "bank_transfer",
      },
    ],
  },
  {
    key: "overdueMorgan",
    customerKey: "morgan",
    jobKey: "completedMorganGfci",
    invoiceNumber: "INV-DEMO-3008",
    status: "overdue",
    subtotal: 165,
    amountPaid: 0,
    issueDaysAgo: 25,
    dueDaysFromNow: -10,
    notes: "GFCI outlet replacement — past due; follow up for payment.",
    lineItems: [
      {
        serviceItemKey: "gfci-outlet",
        name: "GFCI Outlet Replacement",
        description: "Replace failed bathroom GFCI outlet.",
        quantity: 1,
        unitPrice: 165,
      },
    ],
  },
  {
    key: "sentMaple",
    customerKey: "maple",
    jobKey: "completedMapleBreaker",
    invoiceNumber: "INV-DEMO-3009",
    status: "sent",
    subtotal: 159,
    amountPaid: 0,
    issueDaysAgo: 5,
    dueDaysFromNow: 25,
    notes: "Breaker troubleshooting — invoice sent to property management.",
    lineItems: [
      {
        serviceItemKey: "breaker-troubleshoot",
        name: "Breaker Troubleshooting",
        description: "Diagnose overloaded kitchen circuit in unit 18.",
        quantity: 1,
        unitPrice: 159,
      },
    ],
  },
  {
    key: "paidClinic",
    customerKey: "clinic",
    jobKey: "completedClinicEmergency",
    invoiceNumber: "INV-DEMO-3010",
    status: "paid",
    subtotal: 195,
    amountPaid: 0,
    issueDaysAgo: 65,
    dueDaysFromNow: -35,
    paidDaysAgo: 60,
    notes: "Emergency exit sign replacement — paid via ACH.",
    lineItems: [
      {
        serviceItemKey: "light-fixture",
        name: "Light Fixture Replacement",
        description: "Replace emergency exit sign fixtures.",
        quantity: 1,
        unitPrice: 195,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 60,
        reference: "DEMO-PAY-3010",
        notes: "Paid via ACH — medical office billing.",
        paymentMethod: "bank_transfer",
      },
    ],
  },
];

export const ELECTRICAL_DEMO_NOTIFICATIONS: NotificationSeed[] = [
  {
    type: "job_assigned",
    title: "Job assigned",
    message: "You were assigned JOB-DEMO-1001 — Breaker Troubleshooting for Alex Mercer.",
    entityType: "job",
    jobKey: "breakerToday",
  },
  {
    type: "job_completed",
    title: "Job completed",
    message: "JOB-DEMO-1032 outlet replacement completed at Summit Property Group.",
    entityType: "job",
    jobKey: "completedTodaySummit",
  },
  {
    type: "invoice_paid",
    title: "Payment received",
    message: "INV-DEMO-3001 was paid in full.",
    entityType: "invoice",
    invoiceKey: "paidDiag",
  },
  {
    type: "job_completed",
    title: "Job completed",
    message: "JOB-DEMO-1037 outdoor GFCI replacement completed for Alex Mercer.",
    entityType: "job",
    jobKey: "completedTodayAlex",
  },
  {
    type: "invoice_paid",
    title: "Payment received",
    message: "INV-DEMO-3005 was paid in full.",
    entityType: "invoice",
    invoiceKey: "paidBlake",
  },
  {
    type: "job_completed",
    title: "Job completed",
    message: "JOB-DEMO-1017 dedicated circuit installation completed at Corner Table Eatery.",
    entityType: "job",
    jobKey: "completedCornerDedicated",
  },
];

export const ELECTRICAL_DEMO_SEED_PACK = {
  serviceItems: ELECTRICAL_DEMO_SERVICE_ITEMS,
  customers: ELECTRICAL_DEMO_CUSTOMERS,
  leads: ELECTRICAL_DEMO_LEADS,
  equipment: ELECTRICAL_DEMO_EQUIPMENT,
  jobs: ELECTRICAL_DEMO_JOBS,
  materials: ELECTRICAL_DEMO_MATERIALS,
  estimates: ELECTRICAL_DEMO_ESTIMATES,
  invoices: ELECTRICAL_DEMO_INVOICES,
  notifications: ELECTRICAL_DEMO_NOTIFICATIONS,
};
