import type {
  CustomerSeed,
  EquipmentSeed,
  JobSeed,
  LeadSeed,
  ServiceItemSeed,
} from "@/lib/database/services/demo-data-seed-definitions";

export const ELECTRICAL_DEMO_SERVICE_ITEMS: ServiceItemSeed[] = [
  {
    key: "panel-inspection",
    name: "Panel Inspection",
    description: "Visual inspection of main panel, breakers, and bonding.",
    unitPrice: 149,
    category: "Inspection",
  },
  {
    key: "outlet-replacement",
    name: "Outlet Replacement",
    description: "Replace standard duplex outlet and verify wiring.",
    unitPrice: 125,
    unitCost: 8,
    category: "Repair",
  },
  {
    key: "gfci-outlet",
    name: "GFCI Outlet Replacement",
    description: "Replace failed GFCI outlet and test trip/reset function.",
    unitPrice: 165,
    unitCost: 22,
    category: "Repair",
  },
  {
    key: "dedicated-circuit",
    name: "Dedicated Circuit Installation",
    description: "Run new dedicated circuit from panel to equipment location.",
    unitPrice: 425,
    category: "Installation",
  },
  {
    key: "ev-charger",
    name: "EV Charger Installation",
    description: "Install Level 2 EV charger with dedicated circuit and permit.",
    unitPrice: 1850,
    category: "Installation",
  },
  {
    key: "ceiling-fan",
    name: "Ceiling Fan Installation",
    description: "Mount ceiling fan and connect to existing or new switch leg.",
    unitPrice: 275,
    category: "Installation",
  },
  {
    key: "light-fixture",
    name: "Light Fixture Replacement",
    description: "Remove old fixture and install customer-supplied replacement.",
    unitPrice: 195,
    category: "Installation",
  },
  {
    key: "breaker-troubleshoot",
    name: "Breaker Troubleshooting",
    description: "Diagnose tripping breaker and trace overloaded or faulted circuit.",
    unitPrice: 159,
    category: "Service",
  },
  {
    key: "smoke-detector",
    name: "Smoke Detector Installation",
    description: "Install hardwired interconnected smoke detectors per code.",
    unitPrice: 145,
    category: "Installation",
  },
  {
    key: "subpanel",
    name: "Subpanel Installation",
    description: "Install subpanel with feeder and grounding for expanded capacity.",
    unitPrice: 2200,
    category: "Installation",
  },
  {
    key: "recessed-lighting",
    name: "Recessed Lighting Installation",
    description: "Install recessed can lights with new switch leg and trim.",
    unitPrice: 325,
    category: "Installation",
  },
  {
    key: "panel-upgrade",
    name: "Panel Upgrade",
    description: "Replace aging panel with modern load center and breakers.",
    unitPrice: 3800,
    category: "Installation",
  },
  {
    key: "safety-inspection",
    name: "Electrical Safety Inspection",
    description: "Whole-home electrical safety walkthrough for rental turnover.",
    unitPrice: 199,
    category: "Inspection",
  },
  {
    key: "labor",
    name: "Standard Labor Rate",
    description: "Billable electrician labor per hour.",
    unitPrice: 105,
    category: "Labor",
  },
  {
    key: "whole-home-surge",
    name: "Whole-Home Surge Protector",
    description: "Install panel-mounted surge protection device.",
    unitPrice: 485,
    category: "Installation",
  },
  {
    key: "generator-interlock",
    name: "Generator Interlock Kit",
    description: "Install manual transfer interlock for portable generator backup.",
    unitPrice: 650,
    category: "Installation",
  },
];

export const ELECTRICAL_DEMO_CUSTOMERS: CustomerSeed[] = [
  {
    key: "alex",
    name: "Alex Mercer",
    phone: "(512) 555-2101",
    status: "active",
    address: "1200 Demo Ridge Dr",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    tags: ["Residential", "Electrical"],
    notes: "Prefers morning appointments. Gate code on file for demo access.",
    totalJobs: 7,
    totalRevenue: 3420,
    lastServiceDaysAgo: 14,
    createdDaysAgo: 180,
  },
  {
    key: "reese",
    name: "Reese Dalton",
    phone: "(512) 555-2102",
    status: "active",
    address: "88 Sample Oak Ln",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    tags: ["Residential", "Electrical"],
    notes: "Older home with mixed wiring. Interested in panel upgrade quote.",
    totalJobs: 3,
    totalRevenue: 1180,
    lastServiceDaysAgo: 45,
    createdDaysAgo: 140,
  },
  {
    key: "summit",
    name: "Summit Property Group",
    phone: "(512) 555-2103",
    companyName: "Summit Property Group",
    status: "active",
    address: "500 Demo Commerce Blvd",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    tags: ["Property Management", "Multi-unit"],
    notes: "Net-15 billing. Call leasing office before on-site visits.",
    totalJobs: 22,
    totalRevenue: 18650,
    lastServiceDaysAgo: 3,
    createdDaysAgo: 340,
  },
  {
    key: "harbor",
    name: "Harbor Office Suites",
    phone: "(512) 555-2104",
    companyName: "Harbor Office Suites LLC",
    status: "active",
    address: "2100 Demo Business Pkwy, Ste 400",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    tags: ["Commercial", "Office"],
    notes: "Small office suite. After-hours access via loading dock.",
    totalJobs: 10,
    totalRevenue: 8920,
    lastServiceDaysAgo: 0,
    createdDaysAgo: 260,
  },
  {
    key: "blake",
    name: "Blake & Dana Foster",
    phone: "(512) 555-2105",
    status: "active",
    address: "3400 Demo Hollow Ct",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    tags: ["Residential", "Electrical"],
    notes: "Two-story home with workshop in garage. Text before arrival.",
    totalJobs: 5,
    totalRevenue: 2640,
    lastServiceDaysAgo: 10,
    createdDaysAgo: 130,
  },
  {
    key: "morgan",
    name: "Morgan Ellis",
    phone: "(512) 555-2106",
    status: "active",
    address: "615 Demo Meadow Way",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    tags: ["Residential", "Electrical"],
    notes: "New homeowner. Interested in recessed lighting in kitchen.",
    totalJobs: 2,
    totalRevenue: 890,
    lastServiceDaysAgo: 18,
    createdDaysAgo: 75,
  },
  {
    key: "cedar",
    name: "Cedar Grove HOA",
    phone: "(512) 555-2107",
    companyName: "Cedar Grove Property Management",
    status: "active",
    address: "7700 Demo Grove Pkwy",
    city: "Austin",
    state: "TX",
    postalCode: "78749",
    tags: ["Property Management", "Multi-unit"],
    notes: "Clubhouse and common-area electrical on quarterly contract.",
    totalJobs: 16,
    totalRevenue: 13200,
    lastServiceDaysAgo: 32,
    createdDaysAgo: 300,
  },
  {
    key: "market",
    name: "Market Street Studios",
    phone: "(512) 555-2108",
    companyName: "Market Street Studios LLC",
    status: "active",
    address: "900 Demo Executive Blvd, Bldg B",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    tags: ["Commercial", "Small Business"],
    notes: "Creative studio space. Panel and subpanel in utility closet.",
    totalJobs: 6,
    totalRevenue: 5480,
    lastServiceDaysAgo: 28,
    createdDaysAgo: 210,
  },
  {
    key: "corner",
    name: "Corner Table Eatery",
    phone: "(512) 555-2109",
    companyName: "Corner Table Demo Group",
    status: "active",
    address: "42 Demo Main St",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    tags: ["Commercial", "Restaurant"],
    notes: "Kitchen and dining-area circuits. After 2 PM for non-emergency.",
    totalJobs: 6,
    totalRevenue: 4920,
    lastServiceDaysAgo: 0,
    createdDaysAgo: 190,
  },
  {
    key: "storefront",
    name: "Demo Street Boutique",
    phone: "(512) 555-2110",
    companyName: "Demo Street Retail Co.",
    status: "active",
    address: "118 Demo Main St, Unit 2",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    tags: ["Commercial", "Retail"],
    notes: "Street-front retail. Panel in back storage room.",
    totalJobs: 4,
    totalRevenue: 3100,
    lastServiceDaysAgo: 55,
    createdDaysAgo: 170,
  },
  {
    key: "parker",
    name: "Parker Family Residence",
    phone: "(512) 555-2111",
    status: "active",
    address: "880 Demo River Bend Cir",
    city: "Austin",
    state: "TX",
    postalCode: "78744",
    tags: ["Residential", "Electrical"],
    notes: "Referral from Alex Mercer. EV charger install scheduled.",
    totalJobs: 2,
    totalRevenue: 720,
    lastServiceDaysAgo: 40,
    createdDaysAgo: 55,
  },
  {
    key: "maple",
    name: "Maple Court Apartments",
    phone: "(512) 555-2112",
    companyName: "Maple Court Residential Mgmt",
    status: "active",
    address: "3300 Demo Maple Ave",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    tags: ["Property Management", "Multi-unit"],
    notes: "36-unit complex. Electrical room access via leasing office.",
    totalJobs: 12,
    totalRevenue: 10450,
    lastServiceDaysAgo: 70,
    createdDaysAgo: 280,
  },
  {
    key: "workspace",
    name: "Demo Workspace Hub",
    phone: "(512) 555-2113",
    companyName: "Demo Workspace Hub LLC",
    status: "active",
    address: "1500 Demo Innovation Way, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78758",
    tags: ["Commercial", "Small Business"],
    notes: "Coworking space with subpanel for server room.",
    totalJobs: 5,
    totalRevenue: 6200,
    lastServiceDaysAgo: 80,
    createdDaysAgo: 200,
  },
  {
    key: "clinic",
    name: "Demo Family Clinic",
    phone: "(512) 555-2114",
    companyName: "Demo Family Clinic PA",
    status: "active",
    address: "2200 Demo Westlake Dr, Ste 105",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    tags: ["Commercial", "Medical"],
    notes: "Medical office suite. Emergency lighting on annual contract.",
    totalJobs: 8,
    totalRevenue: 7800,
    lastServiceDaysAgo: 62,
    createdDaysAgo: 250,
  },
];

export const ELECTRICAL_DEMO_LEADS: LeadSeed[] = [
  {
    key: "newLead",
    firstName: "Casey",
    lastName: "Brooks",
    phone: "(512) 555-8821",
    source: "google",
    status: "estimate_sent",
    notes: "Panel upgrade estimate sent — homeowner reviewing financing options.",
    createdDaysAgo: 4,
  },
  {
    key: "estimateSentLead",
    firstName: "Jordan",
    lastName: "Reeves",
    phone: "(512) 555-0311",
    source: "referral",
    status: "estimate_sent",
    notes: "EV charger installation quote sent — garage layout confirmed on phone.",
    convertedCustomerKey: "parker",
    createdDaysAgo: 12,
  },
  {
    key: "lostLead",
    firstName: "Riley",
    lastName: "Price",
    phone: "(737) 555-4410",
    source: "facebook",
    status: "estimate_sent",
    notes: "Recessed lighting package quote sent — install window requested for next week.",
    convertedCustomerKey: "morgan",
    createdDaysAgo: 8,
  },
];

export const ELECTRICAL_DEMO_EQUIPMENT: EquipmentSeed[] = [
  {
    customerKey: "alex",
    name: "Main Electrical Panel",
    equipmentType: "Load Center",
    brand: "Square D",
    modelNumber: "QO130L200PG",
    serialNumber: "DEMO-EL-2201",
    installDaysAgo: 1825,
    location: "Garage — east wall",
  },
  {
    customerKey: "reese",
    name: "Main Service Panel",
    equipmentType: "Load Center",
    brand: "Siemens",
    modelNumber: "P3040B1200CU",
    serialNumber: "DEMO-EL-5512",
    installDaysAgo: 4380,
    location: "Exterior — side of house",
  },
  {
    customerKey: "summit",
    name: "Building C Main Panel",
    equipmentType: "Load Center",
    brand: "Eaton",
    modelNumber: "BR4040B200",
    serialNumber: "DEMO-EL-7710",
    installDaysAgo: 1095,
    location: "Utility room — Building C",
  },
  {
    customerKey: "harbor",
    name: "Suite 400 Subpanel",
    equipmentType: "Subpanel",
    brand: "Square D",
    modelNumber: "HOM3060M200PC",
    serialNumber: "DEMO-EL-8834",
    installDaysAgo: 540,
    location: "Electrical closet — Suite 400",
  },
  {
    customerKey: "blake",
    name: "Workshop Subpanel",
    equipmentType: "Subpanel",
    brand: "Siemens",
    modelNumber: "SN2040B1200",
    serialNumber: "DEMO-EL-3341",
    installDaysAgo: 730,
    location: "Garage workshop wall",
  },
  {
    customerKey: "morgan",
    name: "Main Electrical Panel",
    equipmentType: "Load Center",
    brand: "GE",
    modelNumber: "TM2010CCU",
    serialNumber: "DEMO-EL-4452",
    installDaysAgo: 2555,
    location: "Laundry room",
  },
  {
    customerKey: "cedar",
    name: "Clubhouse Main Panel",
    equipmentType: "Load Center",
    brand: "Square D",
    modelNumber: "QO142M200PC",
    serialNumber: "DEMO-EL-5563",
    installDaysAgo: 900,
    location: "Clubhouse utility room",
  },
  {
    customerKey: "market",
    name: "Building B Main Panel",
    equipmentType: "Load Center",
    brand: "Eaton",
    modelNumber: "BR3240B200",
    serialNumber: "DEMO-EL-6674",
    installDaysAgo: 480,
    location: "Building B electrical room",
  },
  {
    customerKey: "corner",
    name: "Kitchen Subpanel",
    equipmentType: "Subpanel",
    brand: "Square D",
    modelNumber: "HOM2040M200PC",
    serialNumber: "DEMO-EL-7785",
    installDaysAgo: 720,
    location: "Kitchen back-of-house",
  },
  {
    customerKey: "storefront",
    name: "Retail Main Panel",
    equipmentType: "Load Center",
    brand: "Siemens",
    modelNumber: "P1224B1100CU",
    serialNumber: "DEMO-EL-8896",
    installDaysAgo: 650,
    location: "Back storage room",
  },
  {
    customerKey: "parker",
    name: "Garage EV Charger Circuit",
    equipmentType: "EV Charger",
    brand: "ChargePoint",
    modelNumber: "Home Flex",
    serialNumber: "DEMO-EL-9907",
    installDaysAgo: 45,
    warrantyDaysFromNow: 320,
    location: "Garage — left wall",
  },
  {
    customerKey: "maple",
    name: "Building Main Service",
    equipmentType: "Load Center",
    brand: "Square D",
    modelNumber: "QO142M200PC",
    serialNumber: "DEMO-EL-1018",
    installDaysAgo: 1500,
    location: "Electrical room — basement",
  },
  {
    customerKey: "workspace",
    name: "Server Room Subpanel",
    equipmentType: "Subpanel",
    brand: "Eaton",
    modelNumber: "BR2040B200",
    serialNumber: "DEMO-EL-1129",
    installDaysAgo: 360,
    warrantyDaysFromNow: 200,
    location: "Server room — Suite 200",
  },
  {
    customerKey: "clinic",
    name: "Medical Suite Panel",
    equipmentType: "Load Center",
    brand: "Siemens",
    modelNumber: "P2040B1200CU",
    serialNumber: "DEMO-EL-1230",
    installDaysAgo: 420,
    location: "Suite 105 utility closet",
  },
];

export const ELECTRICAL_DEMO_JOBS: JobSeed[] = [
  {
    key: "breakerToday",
    customerKey: "alex",
    jobNumber: "JOB-DEMO-1001",
    serviceAddress: "1200 Demo Ridge Dr",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Breaker Troubleshooting",
    scheduledDaysFromNow: 0,
    scheduledHour: 9,
    status: "scheduled",
    description: "Kitchen breaker keeps tripping — trace overloaded circuit.",
    notes: "Customer reports trips when using microwave and toaster together.",
    createdDaysAgo: 2,
  },
  {
    key: "gfciActive",
    customerKey: "harbor",
    jobNumber: "JOB-DEMO-1002",
    serviceAddress: "2100 Demo Business Pkwy, Ste 400",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    jobType: "GFCI Outlet Replacement",
    scheduledDaysFromNow: 0,
    scheduledHour: 8,
    status: "in_progress",
    description: "Replace failed GFCI outlets in break room and restroom.",
    notes: "Two outlets not resetting. Verify line/load wiring on each.",
    createdDaysAgo: 1,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 22,
  },
  {
    key: "safetyInspectionToday",
    customerKey: "clinic",
    jobNumber: "JOB-DEMO-1039",
    serviceAddress: "2200 Demo Westlake Dr, Ste 105",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Electrical Safety Inspection",
    scheduledDaysFromNow: 0,
    scheduledHour: 15,
    status: "scheduled",
    description: "Annual emergency lighting and exit sign inspection.",
    notes: "Medical office suite — follow site access protocols.",
    createdDaysAgo: 3,
  },
  {
    key: "completedTodayMorgan",
    customerKey: "morgan",
    jobNumber: "JOB-DEMO-1030",
    serviceAddress: "615 Demo Meadow Way",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Recessed Lighting Installation",
    scheduledDaysFromNow: 0,
    scheduledHour: 7,
    status: "completed",
    description: "Install four recessed can lights in kitchen ceiling.",
    createdDaysAgo: 2,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 145,
    completionNotes: "Four cans installed with dimmer switch. All circuits tested.",
  },
  {
    key: "completedTodayBlake",
    customerKey: "blake",
    jobNumber: "JOB-DEMO-1031",
    serviceAddress: "3400 Demo Hollow Ct",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    jobType: "Dedicated Circuit Installation",
    scheduledDaysFromNow: 0,
    scheduledHour: 7,
    scheduledMinute: 30,
    status: "completed",
    description: "Add dedicated 20A circuit for workshop table saw.",
    createdDaysAgo: 3,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 165,
    completionNotes: "New circuit run from subpanel. Outlet tested at full load.",
  },
  {
    key: "completedTodaySummit",
    customerKey: "summit",
    jobNumber: "JOB-DEMO-1032",
    serviceAddress: "500 Demo Commerce Blvd, Unit 8B",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "Outlet Replacement",
    scheduledDaysFromNow: 0,
    scheduledHour: 8,
    status: "completed",
    description: "Replace damaged outlets in rental unit turnover.",
    createdDaysAgo: 2,
    arrivedMinutesAfterStart: 6,
    workStartedMinutesAfterStart: 14,
    completedMinutesAfterStart: 75,
    completionNotes: "Three outlets replaced. GFCI tested in kitchen and bath.",
  },
  {
    key: "completedTodayCedar",
    customerKey: "cedar",
    jobNumber: "JOB-DEMO-1033",
    serviceAddress: "7700 Demo Grove Pkwy — Clubhouse",
    city: "Austin",
    state: "TX",
    postalCode: "78749",
    jobType: "Panel Inspection",
    scheduledDaysFromNow: 0,
    scheduledHour: 9,
    status: "completed",
    description: "Quarterly clubhouse panel inspection and breaker torque check.",
    createdDaysAgo: 4,
    arrivedMinutesAfterStart: 7,
    workStartedMinutesAfterStart: 15,
    completedMinutesAfterStart: 90,
    completionNotes: "Panel clean. All breakers torqued and labeled. No issues found.",
  },
  {
    key: "completedTodayMarket",
    customerKey: "market",
    jobNumber: "JOB-DEMO-1034",
    serviceAddress: "900 Demo Executive Blvd, Bldg B",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Light Fixture Replacement",
    scheduledDaysFromNow: 0,
    scheduledHour: 10,
    status: "completed",
    description: "Replace failed LED fixtures in studio common area.",
    createdDaysAgo: 3,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 68,
    completionNotes: "Six fixtures replaced. Ballast bypass verified on each.",
  },
  {
    key: "completedTodayStorefront",
    customerKey: "storefront",
    jobNumber: "JOB-DEMO-1035",
    serviceAddress: "118 Demo Main St, Unit 2",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Breaker Troubleshooting",
    scheduledDaysFromNow: 0,
    scheduledHour: 10,
    scheduledMinute: 30,
    status: "completed",
    description: "Display lighting circuit intermittent — flickering lights troubleshooting.",
    createdDaysAgo: 2,
    arrivedMinutesAfterStart: 6,
    workStartedMinutesAfterStart: 14,
    completedMinutesAfterStart: 72,
    completionNotes: "Loose neutral in junction box repaired. Display lights stable.",
  },
  {
    key: "completedTodayParker",
    customerKey: "parker",
    jobNumber: "JOB-DEMO-1036",
    serviceAddress: "880 Demo River Bend Cir",
    city: "Austin",
    state: "TX",
    postalCode: "78744",
    jobType: "EV Charger Installation",
    scheduledDaysFromNow: 0,
    scheduledHour: 11,
    status: "completed",
    description: "Install Level 2 EV charger in garage with dedicated circuit.",
    createdDaysAgo: 5,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 195,
    completionNotes: "50A circuit installed. Charger commissioned and tested.",
  },
  {
    key: "completedTodayAlex",
    customerKey: "alex",
    jobNumber: "JOB-DEMO-1037",
    serviceAddress: "1200 Demo Ridge Dr",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "GFCI Outlet Replacement",
    scheduledDaysFromNow: 0,
    scheduledHour: 11,
    scheduledMinute: 30,
    status: "completed",
    description: "Replace outdoor GFCI outlet on back patio.",
    createdDaysAgo: 1,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 48,
    completionNotes: "Weather-resistant GFCI installed and tested. Cover plate replaced.",
  },
  {
    key: "completedTodayCorner",
    customerKey: "corner",
    jobNumber: "JOB-DEMO-1038",
    serviceAddress: "42 Demo Main St",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Smoke Detector Installation",
    scheduledDaysFromNow: 0,
    scheduledHour: 12,
    status: "completed",
    description: "Install hardwired smoke detectors in kitchen prep area.",
    createdDaysAgo: 3,
    arrivedMinutesAfterStart: 6,
    workStartedMinutesAfterStart: 14,
    completedMinutesAfterStart: 85,
    completionNotes: "Two detectors installed and interconnected with existing system.",
  },
  {
    key: "evChargerTomorrow",
    customerKey: "parker",
    jobNumber: "JOB-DEMO-1003",
    serviceAddress: "880 Demo River Bend Cir",
    city: "Austin",
    state: "TX",
    postalCode: "78744",
    jobType: "EV Charger Installation",
    scheduledDaysFromNow: 1,
    scheduledHour: 11,
    status: "scheduled",
    description: "Second EV charger install for guest parking area.",
    notes: "Permit pulled. 60A breaker on order.",
    createdDaysAgo: 1,
  },
  {
    key: "dedicatedCircuitTomorrow",
    customerKey: "blake",
    jobNumber: "JOB-DEMO-1004",
    serviceAddress: "3400 Demo Hollow Ct",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    jobType: "Dedicated Circuit Installation",
    scheduledDaysFromNow: 1,
    scheduledHour: 14,
    status: "scheduled",
    description: "Add dedicated circuit for workshop welding equipment.",
    notes: "Customer confirmed 240V outlet location on north wall.",
    createdDaysAgo: 2,
  },
  {
    key: "gfciOutdoorTomorrow",
    customerKey: "summit",
    jobNumber: "JOB-DEMO-1005",
    serviceAddress: "500 Demo Commerce Blvd, Building C",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "GFCI Outlet Replacement",
    scheduledDaysFromNow: 1,
    scheduledHour: 15,
    scheduledMinute: 30,
    status: "scheduled",
    description: "Replace outdoor GFCI outlet at pool equipment area.",
    notes: "In-use cover required. Parts on truck.",
    createdDaysAgo: 2,
  },
  {
    key: "flickeringTomorrow",
    customerKey: "corner",
    jobNumber: "JOB-DEMO-1006",
    serviceAddress: "42 Demo Main St",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Breaker Troubleshooting",
    scheduledDaysFromNow: 1,
    scheduledHour: 10,
    status: "scheduled",
    description: "Flickering lights in dining area — trace voltage drop on branch circuit.",
    notes: "Restaurant after 2 PM for non-emergency access.",
    createdDaysAgo: 1,
  },
  {
    key: "panelQuoteTomorrow",
    customerKey: "reese",
    jobNumber: "JOB-DEMO-1007",
    serviceAddress: "88 Sample Oak Ln",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    jobType: "Panel Upgrade Estimate",
    scheduledDaysFromNow: 1,
    scheduledHour: 10,
    status: "scheduled",
    description: "On-site assessment for 200A panel upgrade estimate.",
    notes: "Bring load calculation worksheet. Existing panel is 100A.",
    createdDaysAgo: 5,
  },
  {
    key: "rentalInspectionTomorrow",
    customerKey: "maple",
    jobNumber: "JOB-DEMO-1008",
    serviceAddress: "3300 Demo Maple Ave, Unit 12",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    jobType: "Electrical Safety Inspection",
    scheduledDaysFromNow: 1,
    scheduledHour: 13,
    status: "scheduled",
    priority: "high",
    description: "Rental property safety inspection before new tenant move-in.",
    notes: "Check all GFCI outlets, smoke detectors, and panel condition.",
    createdDaysAgo: 2,
  },
  {
    key: "recessedFuture",
    customerKey: "morgan",
    jobNumber: "JOB-DEMO-1009",
    serviceAddress: "615 Demo Meadow Way",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Recessed Lighting Installation",
    scheduledDaysFromNow: 3,
    scheduledHour: 9,
    status: "scheduled",
    description: "Install recessed lighting in living room — six cans with dimmer.",
    notes: "Customer selected trim style — verify on arrival.",
    createdDaysAgo: 4,
  },
  {
    key: "ceilingFanFuture",
    customerKey: "alex",
    jobNumber: "JOB-DEMO-1010",
    serviceAddress: "1200 Demo Ridge Dr",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Ceiling Fan Installation",
    scheduledDaysFromNow: 5,
    scheduledHour: 11,
    status: "scheduled",
    description: "Install ceiling fan in master bedroom with remote control.",
    notes: "Fan on site in garage. Confirm ceiling box rating.",
    createdDaysAgo: 6,
  },
  {
    key: "completedBlakeBreaker",
    customerKey: "blake",
    jobNumber: "JOB-DEMO-1011",
    serviceAddress: "3400 Demo Hollow Ct",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    jobType: "Breaker Troubleshooting",
    scheduledDaysFromNow: -12,
    scheduledHour: 14,
    status: "completed",
    priority: "urgent",
    description: "Workshop breaker keeps tripping when table saw starts.",
    createdDaysAgo: 14,
    arrivedMinutesAfterStart: 15,
    workStartedMinutesAfterStart: 28,
    completedMinutesAfterStart: 110,
    completionNotes: "Undersized breaker replaced with correct 20A. Saw starts without trip.",
  },
  {
    key: "completedMorganGfci",
    customerKey: "morgan",
    jobNumber: "JOB-DEMO-1012",
    serviceAddress: "615 Demo Meadow Way",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "GFCI Outlet Replacement",
    scheduledDaysFromNow: -15,
    scheduledHour: 10,
    status: "completed",
    priority: "high",
    description: "Bathroom GFCI outlet not resetting after power outage.",
    createdDaysAgo: 17,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 16,
    completedMinutesAfterStart: 52,
    completionNotes: "GFCI replaced. Downstream outlets tested and labeled.",
  },
  {
    key: "completedAlexPanel",
    customerKey: "alex",
    jobNumber: "JOB-DEMO-1013",
    serviceAddress: "1200 Demo Ridge Dr",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Panel Inspection",
    scheduledDaysFromNow: -18,
    scheduledHour: 13,
    status: "completed",
    description: "Annual panel inspection and surge protector check.",
    createdDaysAgo: 22,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 75,
    completionNotes: "Panel in good condition. Surge protector status LED green.",
  },
  {
    key: "completedSummitInspection",
    customerKey: "summit",
    jobNumber: "JOB-DEMO-1014",
    serviceAddress: "500 Demo Commerce Blvd, Unit 14B",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "Electrical Safety Inspection",
    scheduledDaysFromNow: -25,
    scheduledHour: 10,
    status: "completed",
    description: "Rental property safety inspection for unit turnover.",
    createdDaysAgo: 28,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 95,
    completionNotes: "All GFCI and smoke detectors passed. Minor outlet cover noted for follow-up.",
  },
  {
    key: "completedMarketSubpanel",
    customerKey: "market",
    jobNumber: "JOB-DEMO-1015",
    serviceAddress: "900 Demo Executive Blvd, Bldg B",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Subpanel Installation",
    scheduledDaysFromNow: -30,
    scheduledHour: 8,
    status: "completed",
    description: "Install subpanel for expanded studio lighting circuits.",
    createdDaysAgo: 33,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 15,
    completedMinutesAfterStart: 240,
    completionNotes: "60A subpanel installed with eight new circuits. Inspected and labeled.",
  },
  {
    key: "completedCedarSmoke",
    customerKey: "cedar",
    jobNumber: "JOB-DEMO-1016",
    serviceAddress: "7700 Demo Grove Pkwy — Clubhouse",
    city: "Austin",
    state: "TX",
    postalCode: "78749",
    jobType: "Smoke Detector Installation",
    scheduledDaysFromNow: -35,
    scheduledHour: 11,
    status: "completed",
    description: "Replace expired smoke detectors in clubhouse common areas.",
    createdDaysAgo: 38,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 85,
    completionNotes: "Four detectors replaced and interconnected. All test buttons verified.",
  },
  {
    key: "completedCornerDedicated",
    customerKey: "corner",
    jobNumber: "JOB-DEMO-1017",
    serviceAddress: "42 Demo Main St",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Dedicated Circuit Installation",
    scheduledDaysFromNow: -38,
    scheduledHour: 9,
    status: "completed",
    priority: "high",
    description: "Add dedicated circuit for new commercial oven.",
    createdDaysAgo: 41,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 22,
    completedMinutesAfterStart: 175,
    completionNotes: "50A circuit installed. Oven connected and tested at full load.",
  },
  {
    key: "completedHarborGfci",
    customerKey: "harbor",
    jobNumber: "JOB-DEMO-1018",
    serviceAddress: "2100 Demo Business Pkwy, Ste 400",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    jobType: "GFCI Outlet Replacement",
    scheduledDaysFromNow: -42,
    scheduledHour: 14,
    status: "completed",
    description: "Replace GFCI outlets in office kitchenette.",
    createdDaysAgo: 45,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 55,
    completionNotes: "Two GFCI outlets replaced. Trip/reset tested on each.",
  },
  {
    key: "completedStorefrontFixture",
    customerKey: "storefront",
    jobNumber: "JOB-DEMO-1019",
    serviceAddress: "118 Demo Main St, Unit 2",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Light Fixture Replacement",
    scheduledDaysFromNow: -48,
    scheduledHour: 15,
    status: "completed",
    priority: "high",
    description: "Replace flickering track lighting in retail display area.",
    createdDaysAgo: 51,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 16,
    completedMinutesAfterStart: 90,
    completionNotes: "Track heads replaced. Flickering resolved — bad transformer removed.",
  },
  {
    key: "completedMapleInspection",
    customerKey: "maple",
    jobNumber: "JOB-DEMO-1020",
    serviceAddress: "3300 Demo Maple Ave, Unit 6",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    jobType: "Electrical Safety Inspection",
    scheduledDaysFromNow: -50,
    scheduledHour: 10,
    status: "completed",
    description: "Rental property safety inspection before lease renewal.",
    createdDaysAgo: 53,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 80,
    completionNotes: "Unit passed inspection. One outlet cover to be replaced by maintenance.",
  },
  {
    key: "completedAlexEv",
    customerKey: "alex",
    jobNumber: "JOB-DEMO-1021",
    serviceAddress: "1200 Demo Ridge Dr",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "EV Charger Installation",
    scheduledDaysFromNow: -55,
    scheduledHour: 11,
    status: "completed",
    description: "Install Level 2 EV charger in garage.",
    createdDaysAgo: 58,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 185,
    completionNotes: "40A circuit installed. Charger online and charging verified.",
  },
  {
    key: "completedReeseOutlet",
    customerKey: "reese",
    jobNumber: "JOB-DEMO-1022",
    serviceAddress: "88 Sample Oak Ln",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    jobType: "Outlet Replacement",
    scheduledDaysFromNow: -60,
    scheduledHour: 14,
    status: "completed",
    description: "Replace damaged outlets in home office.",
    createdDaysAgo: 63,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 45,
    completionNotes: "Three outlets replaced. AFCI breakers verified on branch circuits.",
  },
  {
    key: "completedWorkspaceSurge",
    customerKey: "workspace",
    jobNumber: "JOB-DEMO-1023",
    serviceAddress: "1500 Demo Innovation Way, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78758",
    jobType: "Whole-Home Surge Protector",
    scheduledDaysFromNow: -62,
    scheduledHour: 11,
    status: "completed",
    description: "Install panel-mounted surge protector for server room subpanel.",
    createdDaysAgo: 65,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 16,
    completedMinutesAfterStart: 65,
    completionNotes: "Surge protector installed. Status LED confirmed active.",
  },
  {
    key: "completedClinicEmergency",
    customerKey: "clinic",
    jobNumber: "JOB-DEMO-1024",
    serviceAddress: "2200 Demo Westlake Dr, Ste 105",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Light Fixture Replacement",
    scheduledDaysFromNow: -68,
    scheduledHour: 7,
    status: "completed",
    description: "Replace emergency exit sign fixtures in medical suite hallway.",
    createdDaysAgo: 71,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 70,
    completionNotes: "Two exit signs replaced. Battery backup tested on each.",
  },
  {
    key: "completedSummitDedicated",
    customerKey: "summit",
    jobNumber: "JOB-DEMO-1025",
    serviceAddress: "500 Demo Commerce Blvd, Unit 2A",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "Dedicated Circuit Installation",
    scheduledDaysFromNow: -72,
    scheduledHour: 9,
    status: "completed",
    description: "Add dedicated circuit for in-unit washer dryer hookup.",
    createdDaysAgo: 75,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 155,
    completionNotes: "30A circuit installed. Outlet tested. Tenant move-in approved.",
  },
  {
    key: "completedMapleBreaker",
    customerKey: "maple",
    jobNumber: "JOB-DEMO-1026",
    serviceAddress: "3300 Demo Maple Ave, Unit 18",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    jobType: "Breaker Troubleshooting",
    scheduledDaysFromNow: -78,
    scheduledHour: 13,
    status: "completed",
    description: "Unit 18 breaker keeps tripping — overloaded kitchen circuit.",
    createdDaysAgo: 81,
    arrivedMinutesAfterStart: 12,
    workStartedMinutesAfterStart: 25,
    completedMinutesAfterStart: 95,
    completionNotes: "Split overloaded circuit into two branches. No further trips reported.",
  },
  {
    key: "completedWorkspaceSubpanel",
    customerKey: "workspace",
    jobNumber: "JOB-DEMO-1027",
    serviceAddress: "1500 Demo Innovation Way, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78758",
    jobType: "Subpanel Installation",
    scheduledDaysFromNow: -85,
    scheduledHour: 16,
    status: "completed",
    priority: "urgent",
    description: "Server room subpanel overloaded — add capacity for new rack.",
    createdDaysAgo: 88,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 22,
    completedMinutesAfterStart: 210,
    completionNotes: "Subpanel upgraded to 100A. Four new circuits for server rack.",
  },
  {
    key: "completedCornerFan",
    customerKey: "corner",
    jobNumber: "JOB-DEMO-1028",
    serviceAddress: "42 Demo Main St",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Ceiling Fan Installation",
    scheduledDaysFromNow: -88,
    scheduledHour: 14,
    status: "completed",
    description: "Install ceiling fans in dining area for summer comfort.",
    createdDaysAgo: 91,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 16,
    completedMinutesAfterStart: 120,
    completionNotes: "Two fans installed with wall controls. Balanced and quiet.",
  },
  {
    key: "completedHarborPanel",
    customerKey: "harbor",
    jobNumber: "JOB-DEMO-1029",
    serviceAddress: "2100 Demo Business Pkwy, Ste 400",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    jobType: "Panel Inspection",
    scheduledDaysFromNow: -95,
    scheduledHour: 15,
    status: "completed",
    description: "Annual commercial suite panel inspection.",
    createdDaysAgo: 98,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 16,
    completedMinutesAfterStart: 70,
    completionNotes: "Panel and subpanel inspected. All breakers labeled and torqued.",
  },
];
