export type ServiceItemSeed = {
  key: string;
  name: string;
  description: string;
  unitPrice: number;
  category: string;
};

export type CustomerSeed = {
  key: string;
  name: string;
  phone: string;
  companyName?: string;
  status: "active" | "inactive" | "lead";
  address: string;
  city: string;
  state: string;
  postalCode: string;
  tags: string[];
  notes?: string;
  totalJobs: number;
  totalRevenue: number;
  lastServiceDaysAgo?: number;
  createdDaysAgo: number;
};

export type JobSeed = {
  key: string;
  customerKey: string;
  jobNumber: string;
  serviceAddress: string;
  city: string;
  state: string;
  postalCode: string;
  jobType: string;
  scheduledDaysFromNow: number;
  scheduledHour: number;
  scheduledMinute?: number;
  status: "scheduled" | "in_progress" | "completed";
  priority?: "normal" | "high" | "urgent";
  description: string;
  notes?: string;
  createdDaysAgo?: number;
  arrivedMinutesAfterStart?: number;
  workStartedMinutesAfterStart?: number;
  completedMinutesAfterStart?: number;
  completionNotes?: string;
};

export type EquipmentSeed = {
  customerKey: string;
  name: string;
  equipmentType: string;
  brand: string;
  modelNumber: string;
  serialNumber: string;
  installDaysAgo: number;
  warrantyDaysFromNow?: number;
  location: string;
};

export const DEMO_TAX_RATE = 8.25;

export const DEMO_SERVICE_ITEMS: ServiceItemSeed[] = [
  {
    key: "tune-up",
    name: "HVAC Seasonal Tune-Up",
    description: "Full system inspection, filter change, and performance check.",
    unitPrice: 189,
    category: "Maintenance",
  },
  {
    key: "diagnostic",
    name: "AC System Diagnostic",
    description: "Electrical and refrigerant diagnostics for cooling issues.",
    unitPrice: 129,
    category: "Service",
  },
  {
    key: "capacitor",
    name: "Capacitor Replacement",
    description: "Replace failed run capacitor and verify compressor startup.",
    unitPrice: 275,
    category: "Repair",
  },
  {
    key: "furnace",
    name: "Furnace Maintenance",
    description: "Combustion check, heat exchanger inspection, and safety test.",
    unitPrice: 165,
    category: "Maintenance",
  },
  {
    key: "labor",
    name: "Standard Labor Rate",
    description: "Billable technician labor per hour.",
    unitPrice: 95,
    category: "Labor",
  },
  {
    key: "water-heater",
    name: "Water Heater Service",
    description: "Diagnose and repair tank water heater issues.",
    unitPrice: 245,
    category: "Plumbing",
  },
  {
    key: "electrical",
    name: "Electrical Troubleshooting",
    description: "Trace HVAC control circuit and low-voltage wiring faults.",
    unitPrice: 149,
    category: "Electrical",
  },
  {
    key: "system-replacement",
    name: "Packaged RTU Replacement",
    description: "Remove and replace rooftop packaged HVAC unit.",
    unitPrice: 7850,
    category: "Installation",
  },
  {
    key: "furnace-replacement",
    name: "Gas Furnace Replacement",
    description: "High-efficiency furnace replacement with permit and startup.",
    unitPrice: 4200,
    category: "Installation",
  },
  {
    key: "blower-motor",
    name: "Blower Motor Replacement",
    description: "Replace failed ECM blower motor and verify airflow.",
    unitPrice: 685,
    category: "Repair",
  },
  {
    key: "refrigerant-leak",
    name: "Refrigerant Leak Repair",
    description: "Locate leak, repair line set, evacuate, and recharge system.",
    unitPrice: 520,
    category: "Repair",
  },
  {
    key: "thermostat-install",
    name: "Smart Thermostat Install",
    description: "Install and configure Wi-Fi thermostat with C-wire adapter.",
    unitPrice: 325,
    category: "Installation",
  },
  {
    key: "ductwork-repair",
    name: "Ductwork Repair",
    description: "Seal and repair disconnected or damaged supply duct runs.",
    unitPrice: 890,
    category: "Repair",
  },
  {
    key: "maintenance-package",
    name: "Annual Maintenance Package",
    description: "Two seasonal tune-ups plus priority scheduling.",
    unitPrice: 349,
    category: "Maintenance",
  },
  {
    key: "iaq-addon",
    name: "Indoor Air Quality Add-On",
    description: "UV light and MERV-13 media filter upgrade.",
    unitPrice: 1150,
    category: "Installation",
  },
  {
    key: "rtu-repair",
    name: "Commercial RTU Repair",
    description: "Diagnose and repair rooftop packaged unit components.",
    unitPrice: 475,
    category: "Commercial",
  },
  {
    key: "no-heat",
    name: "No Heat Diagnostic & Repair",
    description: "Diagnose heating failure and restore furnace operation.",
    unitPrice: 195,
    category: "Service",
  },
];

export const DEMO_CUSTOMERS: CustomerSeed[] = [
  {
    key: "james",
    name: "James Chen",
    phone: "(737) 555-0198",
    status: "active",
    address: "903 Willow Creek Ln",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    tags: ["Residential", "HVAC"],
    notes: "Prefers afternoon appointments. Dog in backyard — knock first.",
    totalJobs: 9,
    totalRevenue: 4820,
    lastServiceDaysAgo: 18,
    createdDaysAgo: 210,
  },
  {
    key: "emily",
    name: "Emily Rodriguez",
    phone: "(512) 555-0311",
    status: "active",
    address: "221 Sunset Ridge",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    tags: ["Residential", "HVAC"],
    notes: "Older split system. Interested in furnace replacement this fall.",
    totalJobs: 4,
    totalRevenue: 1340,
    lastServiceDaysAgo: 52,
    createdDaysAgo: 160,
  },
  {
    key: "lakewood",
    name: "Lakewood Apartments",
    phone: "(512) 555-0678",
    companyName: "Lakewood Property Management",
    status: "active",
    address: "3200 Lakewood Dr",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    tags: ["Property Management", "Multi-unit"],
    notes: "Net-15 billing. Call maintenance line before arriving on-site.",
    totalJobs: 26,
    totalRevenue: 21480,
    lastServiceDaysAgo: 4,
    createdDaysAgo: 365,
  },
  {
    key: "greenfield",
    name: "Greenfield Dental Studio",
    phone: "(512) 555-0234",
    companyName: "Greenfield Dental Studio",
    status: "active",
    address: "5500 Business Park Blvd, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    tags: ["Commercial", "Medical/Dental"],
    notes: "Small commercial suite. After-hours access via loading dock.",
    totalJobs: 12,
    totalRevenue: 9680,
    lastServiceDaysAgo: 0,
    createdDaysAgo: 280,
  },
  {
    key: "marcus",
    name: "Marcus & Lisa Thompson",
    phone: "(512) 555-0442",
    status: "active",
    address: "1847 Pecan Hollow Dr",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    tags: ["Residential", "HVAC"],
    notes: "Two-story home with dual-zone system. Text before arrival.",
    totalJobs: 6,
    totalRevenue: 2890,
    lastServiceDaysAgo: 12,
    createdDaysAgo: 145,
  },
  {
    key: "sarah",
    name: "Sarah Nguyen",
    phone: "(512) 555-0589",
    status: "active",
    address: "412 Bluebonnet Trail",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    tags: ["Residential", "HVAC"],
    notes: "New homeowner. Interested in smart thermostat upgrade.",
    totalJobs: 3,
    totalRevenue: 1120,
    lastServiceDaysAgo: 15,
    createdDaysAgo: 90,
  },
  {
    key: "ridgewood",
    name: "Ridgewood Estates HOA",
    phone: "(512) 555-0712",
    companyName: "Ridgewood Property Management",
    status: "active",
    address: "8800 Ridgewood Pkwy",
    city: "Austin",
    state: "TX",
    postalCode: "78749",
    tags: ["Property Management", "Multi-unit"],
    notes: "Clubhouse and pool house HVAC on quarterly contract.",
    totalJobs: 18,
    totalRevenue: 15420,
    lastServiceDaysAgo: 38,
    createdDaysAgo: 320,
  },
  {
    key: "sunrise",
    name: "Sunrise Business Center",
    phone: "(512) 555-0823",
    companyName: "Sunrise Business Center LLC",
    status: "active",
    address: "1200 Executive Blvd, Bldg A",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    tags: ["Commercial", "Small Business"],
    notes: "Three-suite office park. Rooftop units on buildings A and B.",
    totalJobs: 8,
    totalRevenue: 6240,
    lastServiceDaysAgo: 30,
    createdDaysAgo: 240,
  },
  {
    key: "bistro84",
    name: "Bistro 84",
    phone: "(512) 555-0934",
    companyName: "Bistro 84 Restaurant Group",
    status: "active",
    address: "84 Main Street",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    tags: ["Commercial", "Restaurant"],
    notes: "Kitchen exhaust and dining-area HVAC. After 2 PM for non-emergency.",
    totalJobs: 7,
    totalRevenue: 5830,
    lastServiceDaysAgo: 0,
    createdDaysAgo: 200,
  },
  {
    key: "mainStreet",
    name: "Main Street Boutique",
    phone: "(512) 555-1045",
    companyName: "Main Street Retail Co.",
    status: "active",
    address: "215 Main Street, Unit 4",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    tags: ["Commercial", "Retail"],
    notes: "Street-front retail space. RTU on roof — ladder access from rear.",
    totalJobs: 5,
    totalRevenue: 3950,
    lastServiceDaysAgo: 60,
    createdDaysAgo: 180,
  },
  {
    key: "chenFamily",
    name: "Chen Family Residence",
    phone: "(737) 555-1156",
    status: "lead",
    address: "6200 River Bend Cir",
    city: "Austin",
    state: "TX",
    postalCode: "78744",
    tags: ["Residential", "HVAC"],
    notes: "Referral from James Chen. First-time customer — spring tune-up scheduled.",
    totalJobs: 2,
    totalRevenue: 680,
    lastServiceDaysAgo: 45,
    createdDaysAgo: 60,
  },
  {
    key: "oakwood",
    name: "Oakwood Apartments",
    phone: "(512) 555-1267",
    companyName: "Oakwood Residential Management",
    status: "active",
    address: "4500 Oakwood Ave",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    tags: ["Property Management", "Multi-unit"],
    notes: "48-unit complex. Boiler room access via leasing office.",
    totalJobs: 14,
    totalRevenue: 11890,
    lastServiceDaysAgo: 78,
    createdDaysAgo: 300,
  },
  {
    key: "techHub",
    name: "TechHub Coworking",
    phone: "(512) 555-1378",
    companyName: "TechHub Austin LLC",
    status: "active",
    address: "900 Innovation Way, Ste 300",
    city: "Austin",
    state: "TX",
    postalCode: "78758",
    tags: ["Commercial", "Small Business"],
    notes: "Open-plan coworking space. VRF system — OEM parts only.",
    totalJobs: 6,
    totalRevenue: 7120,
    lastServiceDaysAgo: 85,
    createdDaysAgo: 220,
  },
  {
    key: "westlake",
    name: "Westlake Family Medicine",
    phone: "(512) 555-1489",
    companyName: "Westlake Family Medicine PA",
    status: "active",
    address: "3801 Westlake Dr, Ste 110",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    tags: ["Commercial", "Medical/Dental"],
    notes: "Medical office suite. Strict infection-control protocols on-site.",
    totalJobs: 9,
    totalRevenue: 8450,
    lastServiceDaysAgo: 68,
    createdDaysAgo: 260,
  },
  {
    key: "platePerfect",
    name: "Plate & Perfect Kitchen",
    phone: "(512) 555-1590",
    companyName: "Plate & Perfect LLC",
    status: "active",
    address: "1600 Foodie Lane",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    tags: ["Commercial", "Restaurant"],
    notes: "Fast-casual restaurant. Grease-laden exhaust requires quarterly cleaning.",
    totalJobs: 4,
    totalRevenue: 3200,
    lastServiceDaysAgo: 88,
    createdDaysAgo: 150,
  },
];

export const DEMO_EQUIPMENT: EquipmentSeed[] = [
  {
    customerKey: "james",
    name: "Heat Pump Split System",
    equipmentType: "Split Heat Pump",
    brand: "Lennox",
    modelNumber: "XP16-036",
    serialNumber: "DEMO-SN-2208",
    installDaysAgo: 820,
    warrantyDaysFromNow: 120,
    location: "Backyard condenser / attic air handler",
  },
  {
    customerKey: "emily",
    name: "Gas Furnace & AC Split",
    equipmentType: "Split System",
    brand: "Goodman",
    modelNumber: "GMEC96 + GSX14",
    serialNumber: "DEMO-SN-5512",
    installDaysAgo: 2400,
    location: "Garage furnace / side-yard condenser",
  },
  {
    customerKey: "lakewood",
    name: "Unit 14B Packaged AC",
    equipmentType: "Packaged AC",
    brand: "Rheem",
    modelNumber: "RALB-036",
    serialNumber: "DEMO-SN-7710",
    installDaysAgo: 1100,
    location: "Roof — Building B",
  },
  {
    customerKey: "greenfield",
    name: "Suite 200 Split System",
    equipmentType: "Split AC",
    brand: "Trane",
    modelNumber: "XR16",
    serialNumber: "DEMO-SN-8834",
    installDaysAgo: 540,
    location: "Mechanical room 2B",
  },
  {
    customerKey: "marcus",
    name: "Dual-Zone Heat Pump",
    equipmentType: "Split Heat Pump",
    brand: "Carrier",
    modelNumber: "25HCE636",
    serialNumber: "DEMO-SN-3341",
    installDaysAgo: 620,
    location: "Side yard condenser / attic handlers",
  },
  {
    customerKey: "sarah",
    name: "Single-Stage AC Split",
    equipmentType: "Split AC",
    brand: "American Standard",
    modelNumber: "Silver 16",
    serialNumber: "DEMO-SN-4452",
    installDaysAgo: 1800,
    location: "Backyard condenser / hall closet air handler",
  },
  {
    customerKey: "ridgewood",
    name: "Clubhouse Packaged Unit",
    equipmentType: "Packaged Gas/Electric",
    brand: "York",
    modelNumber: "ZG120N20R2A",
    serialNumber: "DEMO-SN-5563",
    installDaysAgo: 900,
    location: "Clubhouse roof",
  },
  {
    customerKey: "sunrise",
    name: "Building A RTU",
    equipmentType: "Rooftop Unit",
    brand: "Daikin",
    modelNumber: "RPG120C",
    serialNumber: "DEMO-SN-6674",
    installDaysAgo: 480,
    location: "Building A roof",
  },
  {
    customerKey: "bistro84",
    name: "Kitchen Make-Up Air Unit",
    equipmentType: "Make-Up Air",
    brand: "CaptiveAire",
    modelNumber: "MU-2400",
    serialNumber: "DEMO-SN-7785",
    installDaysAgo: 720,
    location: "Roof above kitchen",
  },
  {
    customerKey: "mainStreet",
    name: "Retail RTU",
    equipmentType: "Rooftop Unit",
    brand: "Trane",
    modelNumber: "YHC120",
    serialNumber: "DEMO-SN-8896",
    installDaysAgo: 650,
    location: "Storefront roof",
  },
  {
    customerKey: "oakwood",
    name: "Boiler & Chiller Plant",
    equipmentType: "Central Plant",
    brand: "Cleaver-Brooks",
    modelNumber: "CB-200",
    serialNumber: "DEMO-SN-9907",
    installDaysAgo: 1500,
    location: "Mechanical room — basement",
  },
  {
    customerKey: "techHub",
    name: "VRF Outdoor Unit",
    equipmentType: "VRF System",
    brand: "Mitsubishi",
    modelNumber: "PUHY-P72",
    serialNumber: "DEMO-SN-1018",
    installDaysAgo: 360,
    warrantyDaysFromNow: 200,
    location: "Roof — east side",
  },
  {
    customerKey: "westlake",
    name: "Medical Suite Split System",
    equipmentType: "Split AC",
    brand: "Daikin",
    modelNumber: "DX16SA",
    serialNumber: "DEMO-SN-1129",
    installDaysAgo: 420,
    location: "Suite 110 mechanical closet",
  },
  {
    customerKey: "platePerfect",
    name: "Restaurant RTU",
    equipmentType: "Rooftop Unit",
    brand: "Lennox",
    modelNumber: "LGH120H2",
    serialNumber: "DEMO-SN-1230",
    installDaysAgo: 580,
    location: "Dining area roof",
  },
];

export const DEMO_JOBS: JobSeed[] = [
  // --- Today ---
  {
    key: "maintenanceToday",
    customerKey: "james",
    jobNumber: "JOB-DEMO-1001",
    serviceAddress: "903 Willow Creek Ln",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "HVAC Maintenance",
    scheduledDaysFromNow: 0,
    scheduledHour: 9,
    status: "scheduled",
    description: "Spring tune-up — filter change, coil cleaning, and performance check.",
    notes: "Annual maintenance visit. Customer prefers afternoon if rescheduled.",
    createdDaysAgo: 3,
  },
  {
    key: "noCoolingActive",
    customerKey: "greenfield",
    jobNumber: "JOB-DEMO-1002",
    serviceAddress: "5500 Business Park Blvd, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    jobType: "AC Repair — No Cooling",
    scheduledDaysFromNow: 0,
    scheduledHour: 8,
    status: "in_progress",
    priority: "urgent",
    description: "Suite AC not cooling. Staff reported 82°F indoor temperature.",
    notes: "Active emergency call. Check rooftop unit and thermostat wiring.",
    createdDaysAgo: 0,
    arrivedMinutesAfterStart: 15,
    workStartedMinutesAfterStart: 35,
  },
  {
    key: "waterHeaterToday",
    customerKey: "lakewood",
    jobNumber: "JOB-DEMO-1003",
    serviceAddress: "3200 Lakewood Dr, Unit 8C",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "Water Heater Repair",
    scheduledDaysFromNow: 0,
    scheduledHour: 11,
    status: "scheduled",
    priority: "high",
    description: "Tenant reports lukewarm water and popping noises from tank.",
    notes: "Property management work order #LM-4421.",
    createdDaysAgo: 1,
  },
  {
    key: "capacitorToday",
    customerKey: "emily",
    jobNumber: "JOB-DEMO-1004",
    serviceAddress: "221 Sunset Ridge",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    jobType: "Capacitor Replacement",
    scheduledDaysFromNow: 0,
    scheduledHour: 14,
    status: "scheduled",
    priority: "high",
    description: "Replace failed run capacitor on outdoor condenser.",
    notes: "Parts on truck. Confirm amp draw after startup.",
    createdDaysAgo: 2,
  },
  {
    key: "electricalToday",
    customerKey: "lakewood",
    jobNumber: "JOB-DEMO-1005",
    serviceAddress: "3200 Lakewood Dr, Building C",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "Electrical Troubleshooting",
    scheduledDaysFromNow: 0,
    scheduledHour: 15,
    scheduledMinute: 30,
    status: "scheduled",
    description: "Intermittent thermostat power loss in common-area HVAC controller.",
    notes: "Check low-voltage transformer and contactor coil.",
    createdDaysAgo: 2,
  },
  {
    key: "noHeatToday",
    customerKey: "bistro84",
    jobNumber: "JOB-DEMO-1006",
    serviceAddress: "84 Main Street",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "No Heat — Furnace Repair",
    scheduledDaysFromNow: 0,
    scheduledHour: 10,
    status: "scheduled",
    priority: "urgent",
    description: "Dining area furnace not firing. Indoor temp dropped to 58°F overnight.",
    notes: "Restaurant opens at 11 AM — priority before lunch service.",
    createdDaysAgo: 0,
  },
  // --- Tomorrow ---
  {
    key: "furnaceQuoteTomorrow",
    customerKey: "emily",
    jobNumber: "JOB-DEMO-1007",
    serviceAddress: "221 Sunset Ridge",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    jobType: "Furnace Replacement Quote",
    scheduledDaysFromNow: 1,
    scheduledHour: 10,
    status: "scheduled",
    description: "On-site measurement and quote for 80% AFUE furnace replacement.",
    notes: "Bring replacement sizing worksheet. Draft estimate ready for review.",
    createdDaysAgo: 5,
  },
  {
    key: "rtuRepairTomorrow",
    customerKey: "mainStreet",
    jobNumber: "JOB-DEMO-1008",
    serviceAddress: "215 Main Street, Unit 4",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Rooftop Unit Repair",
    scheduledDaysFromNow: 1,
    scheduledHour: 13,
    status: "scheduled",
    priority: "high",
    description: "Retail RTU short-cycling. Tenant reports uneven cooling in storefront.",
    notes: "Roof access from rear alley. Bring fall protection.",
    createdDaysAgo: 2,
  },
  // --- Near future ---
  {
    key: "maintenanceFuture",
    customerKey: "chenFamily",
    jobNumber: "JOB-DEMO-1009",
    serviceAddress: "6200 River Bend Cir",
    city: "Austin",
    state: "TX",
    postalCode: "78744",
    jobType: "HVAC Maintenance",
    scheduledDaysFromNow: 3,
    scheduledHour: 9,
    status: "scheduled",
    description: "First visit spring tune-up for new customer referral.",
    notes: "Referred by James Chen. Confirm equipment age on arrival.",
    createdDaysAgo: 4,
  },
  {
    key: "thermostatInstallFuture",
    customerKey: "sarah",
    jobNumber: "JOB-DEMO-1010",
    serviceAddress: "412 Bluebonnet Trail",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Smart Thermostat Install",
    scheduledDaysFromNow: 5,
    scheduledHour: 11,
    status: "scheduled",
    description: "Install Ecobee smart thermostat with C-wire power adapter.",
    notes: "Customer purchased thermostat — verify model on arrival.",
    createdDaysAgo: 6,
  },
  // --- Completed history (~3 months) ---
  {
    key: "completedMarcusNoCool",
    customerKey: "marcus",
    jobNumber: "JOB-DEMO-1011",
    serviceAddress: "1847 Pecan Hollow Dr",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    jobType: "AC Repair — No Cooling",
    scheduledDaysFromNow: -12,
    scheduledHour: 14,
    status: "completed",
    priority: "urgent",
    description: "Upstairs zone not cooling. Compressor running but no cold air.",
    createdDaysAgo: 14,
    arrivedMinutesAfterStart: 20,
    workStartedMinutesAfterStart: 35,
    completedMinutesAfterStart: 125,
    completionNotes: "Low refrigerant due to pinhole leak on line set. Repaired and recharged.",
  },
  {
    key: "completedSarahCap",
    customerKey: "sarah",
    jobNumber: "JOB-DEMO-1012",
    serviceAddress: "412 Bluebonnet Trail",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Capacitor Replacement",
    scheduledDaysFromNow: -15,
    scheduledHour: 10,
    status: "completed",
    priority: "high",
    description: "Outdoor unit humming but fan not spinning — suspected bad capacitor.",
    createdDaysAgo: 17,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 65,
    completionNotes: "45/5 MFD capacitor replaced. Fan and compressor running normally.",
  },
  {
    key: "completedJamesMaint",
    customerKey: "james",
    jobNumber: "JOB-DEMO-1013",
    serviceAddress: "903 Willow Creek Ln",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Furnace Maintenance",
    scheduledDaysFromNow: -18,
    scheduledHour: 13,
    status: "completed",
    description: "Annual furnace maintenance and combustion safety check.",
    createdDaysAgo: 22,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 25,
    completedMinutesAfterStart: 115,
    completionNotes: "Replaced dirty filter and cleaned flame sensor. System operating normally.",
  },
  {
    key: "completedLakewoodDiag",
    customerKey: "lakewood",
    jobNumber: "JOB-DEMO-1014",
    serviceAddress: "3200 Lakewood Dr, Unit 14B",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "HVAC Diagnostic",
    scheduledDaysFromNow: -25,
    scheduledHour: 10,
    status: "completed",
    description: "Diagnose weak cooling in unit 14B and verify airflow balance.",
    createdDaysAgo: 28,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 105,
    completionNotes: "Found restricted return grille. Corrected and verified 18° delta-T.",
  },
  {
    key: "completedSunriseMaint",
    customerKey: "sunrise",
    jobNumber: "JOB-DEMO-1015",
    serviceAddress: "1200 Executive Blvd, Bldg A",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Preventive Maintenance",
    scheduledDaysFromNow: -30,
    scheduledHour: 8,
    status: "completed",
    description: "Quarterly RTU maintenance on Building A rooftop unit.",
    createdDaysAgo: 33,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 15,
    completedMinutesAfterStart: 120,
    completionNotes: "Replaced belts, cleaned coils, verified gas pressure and airflow.",
  },
  {
    key: "completedMarcusTuneUp",
    customerKey: "marcus",
    jobNumber: "JOB-DEMO-1016",
    serviceAddress: "1847 Pecan Hollow Dr",
    city: "Pflugerville",
    state: "TX",
    postalCode: "78660",
    jobType: "HVAC Seasonal Tune-Up",
    scheduledDaysFromNow: -35,
    scheduledHour: 11,
    status: "completed",
    description: "Spring tune-up on dual-zone heat pump system.",
    createdDaysAgo: 38,
    arrivedMinutesAfterStart: 12,
    workStartedMinutesAfterStart: 22,
    completedMinutesAfterStart: 95,
    completionNotes: "Both zones checked. Condenser coil cleaned. Refrigerant levels OK.",
  },
  {
    key: "completedRidgewoodBlower",
    customerKey: "ridgewood",
    jobNumber: "JOB-DEMO-1017",
    serviceAddress: "8800 Ridgewood Pkwy — Clubhouse",
    city: "Austin",
    state: "TX",
    postalCode: "78749",
    jobType: "Blower Motor Replacement",
    scheduledDaysFromNow: -38,
    scheduledHour: 9,
    status: "completed",
    priority: "high",
    description: "Clubhouse packaged unit blower motor seized. No airflow in common areas.",
    createdDaysAgo: 41,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 25,
    completedMinutesAfterStart: 180,
    completionNotes: "ECM blower motor replaced. Verified static pressure within spec.",
  },
  {
    key: "completedGreenfieldMaint",
    customerKey: "greenfield",
    jobNumber: "JOB-DEMO-1018",
    serviceAddress: "5500 Business Park Blvd, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    jobType: "Preventive Maintenance",
    scheduledDaysFromNow: -42,
    scheduledHour: 14,
    status: "completed",
    description: "Quarterly commercial maintenance on split system.",
    createdDaysAgo: 45,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 15,
    completedMinutesAfterStart: 135,
    completionNotes: "Cleaned condenser coil and verified refrigerant charge.",
  },
  {
    key: "completedBistroRefrigerant",
    customerKey: "bistro84",
    jobNumber: "JOB-DEMO-1019",
    serviceAddress: "84 Main Street",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Refrigerant Leak Repair",
    scheduledDaysFromNow: -48,
    scheduledHour: 15,
    status: "completed",
    priority: "high",
    description: "Kitchen make-up air unit losing refrigerant. Dining area overheating.",
    createdDaysAgo: 51,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 165,
    completionNotes: "Leak at flare connection repaired. System evacuated and recharged to spec.",
  },
  {
    key: "completedRidgewoodWater",
    customerKey: "ridgewood",
    jobNumber: "JOB-DEMO-1020",
    serviceAddress: "8800 Ridgewood Pkwy — Pool House",
    city: "Austin",
    state: "TX",
    postalCode: "78749",
    jobType: "Water Heater Service",
    scheduledDaysFromNow: -50,
    scheduledHour: 10,
    status: "completed",
    description: "Pool house water heater not maintaining temperature.",
    createdDaysAgo: 53,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 140,
    completionNotes: "Replaced lower heating element. Anode rod inspected — OK.",
  },
  {
    key: "completedJamesCap",
    customerKey: "james",
    jobNumber: "JOB-DEMO-1021",
    serviceAddress: "903 Willow Creek Ln",
    city: "Round Rock",
    state: "TX",
    postalCode: "78664",
    jobType: "Capacitor Replacement",
    scheduledDaysFromNow: -55,
    scheduledHour: 11,
    status: "completed",
    description: "Replace failed run capacitor on heat pump condenser.",
    createdDaysAgo: 58,
    arrivedMinutesAfterStart: 12,
    workStartedMinutesAfterStart: 22,
    completedMinutesAfterStart: 75,
    completionNotes: "Capacitor replaced. Compressor amp draw within spec.",
  },
  {
    key: "completedMainStreetThermostat",
    customerKey: "mainStreet",
    jobNumber: "JOB-DEMO-1022",
    serviceAddress: "215 Main Street, Unit 4",
    city: "Georgetown",
    state: "TX",
    postalCode: "78626",
    jobType: "Thermostat Install",
    scheduledDaysFromNow: -60,
    scheduledHour: 14,
    status: "completed",
    description: "Replace outdated mercury thermostat with programmable unit.",
    createdDaysAgo: 63,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 55,
    completionNotes: "New thermostat installed and programmed. Heating and cooling verified.",
  },
  {
    key: "completedSunriseElectrical",
    customerKey: "sunrise",
    jobNumber: "JOB-DEMO-1023",
    serviceAddress: "1200 Executive Blvd, Bldg B",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Electrical Troubleshooting",
    scheduledDaysFromNow: -62,
    scheduledHour: 11,
    status: "completed",
    description: "Building B RTU not responding to thermostat call.",
    createdDaysAgo: 65,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 110,
    completionNotes: "Failed contactor replaced. Control voltage verified at 24V.",
  },
  {
    key: "completedWestlakeMaint",
    customerKey: "westlake",
    jobNumber: "JOB-DEMO-1024",
    serviceAddress: "3801 Westlake Dr, Ste 110",
    city: "Austin",
    state: "TX",
    postalCode: "78746",
    jobType: "Preventive Maintenance",
    scheduledDaysFromNow: -68,
    scheduledHour: 7,
    status: "completed",
    description: "Semi-annual maintenance before summer season. Medical office suite.",
    createdDaysAgo: 71,
    arrivedMinutesAfterStart: 5,
    workStartedMinutesAfterStart: 12,
    completedMinutesAfterStart: 100,
    completionNotes: "Filter replaced, drain cleared, UV bulb checked. All systems normal.",
  },
  {
    key: "completedLakewoodWater",
    customerKey: "lakewood",
    jobNumber: "JOB-DEMO-1025",
    serviceAddress: "3200 Lakewood Dr, Unit 2A",
    city: "Austin",
    state: "TX",
    postalCode: "78745",
    jobType: "Water Heater Service",
    scheduledDaysFromNow: -72,
    scheduledHour: 9,
    status: "completed",
    description: "Replace faulty upper thermostat and flush sediment from tank.",
    createdDaysAgo: 75,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 20,
    completedMinutesAfterStart: 150,
    completionNotes: "Thermostat replaced. Tank flushed. Stable hot water confirmed.",
  },
  {
    key: "completedOakwoodDiag",
    customerKey: "oakwood",
    jobNumber: "JOB-DEMO-1026",
    serviceAddress: "4500 Oakwood Ave, Unit 12",
    city: "Austin",
    state: "TX",
    postalCode: "78751",
    jobType: "HVAC Diagnostic",
    scheduledDaysFromNow: -78,
    scheduledHour: 13,
    status: "completed",
    description: "Tenant complaint of no cooling in unit 12. Check central plant loop.",
    createdDaysAgo: 81,
    arrivedMinutesAfterStart: 15,
    workStartedMinutesAfterStart: 30,
    completedMinutesAfterStart: 120,
    completionNotes: "Zone valve stuck closed. Replaced actuator and verified flow.",
  },
  {
    key: "completedTechHubNoCool",
    customerKey: "techHub",
    jobNumber: "JOB-DEMO-1027",
    serviceAddress: "900 Innovation Way, Ste 300",
    city: "Austin",
    state: "TX",
    postalCode: "78758",
    jobType: "AC Repair — No Cooling",
    scheduledDaysFromNow: -85,
    scheduledHour: 16,
    status: "completed",
    priority: "urgent",
    description: "VRF system fault code E6. Open-plan area not cooling.",
    createdDaysAgo: 88,
    arrivedMinutesAfterStart: 10,
    workStartedMinutesAfterStart: 22,
    completedMinutesAfterStart: 145,
    completionNotes: "Communication board fault. Replaced board and cleared error history.",
  },
  {
    key: "completedPlatePerfectMaint",
    customerKey: "platePerfect",
    jobNumber: "JOB-DEMO-1028",
    serviceAddress: "1600 Foodie Lane",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    jobType: "Preventive Maintenance",
    scheduledDaysFromNow: -88,
    scheduledHour: 14,
    status: "completed",
    description: "Quarterly restaurant RTU and exhaust system maintenance.",
    createdDaysAgo: 91,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 130,
    completionNotes: "Coils cleaned, belts adjusted, grease filter inspected.",
  },
  {
    key: "completedGreenfieldElectrical",
    customerKey: "greenfield",
    jobNumber: "JOB-DEMO-1029",
    serviceAddress: "5500 Business Park Blvd, Ste 200",
    city: "Austin",
    state: "TX",
    postalCode: "78759",
    jobType: "Electrical Troubleshooting",
    scheduledDaysFromNow: -95,
    scheduledHour: 15,
    status: "completed",
    description: "Trace intermittent blower motor control circuit fault.",
    createdDaysAgo: 98,
    arrivedMinutesAfterStart: 8,
    workStartedMinutesAfterStart: 18,
    completedMinutesAfterStart: 120,
    completionNotes: "Loose wire nut on relay coil. Repaired and load-tested.",
  },
];
