import {
  DEMO_CUSTOMERS,
  DEMO_EQUIPMENT,
  DEMO_JOBS,
  DEMO_LEADS,
  DEMO_SERVICE_ITEMS,
  type EstimateSeed,
  type InvoiceSeed,
  type MaterialSeed,
  type NotificationSeed,
} from "@/lib/database/services/demo-data-seed-definitions";

export const HVAC_DEMO_MATERIALS: MaterialSeed[] = [
  {
    customerKey: "james",
    jobKey: "completedJamesMaint",
    serviceItemKey: "furnace",
    name: "Furnace filter — 16x25x1",
    quantity: 1,
    unitCost: 18,
    unitPrice: 32,
  },
  {
    customerKey: "james",
    jobKey: "completedJamesCap",
    serviceItemKey: "capacitor",
    name: "45/5 MFD run capacitor",
    quantity: 1,
    unitCost: 42,
    unitPrice: 275,
  },
  {
    customerKey: "greenfield",
    jobKey: "completedGreenfieldMaint",
    serviceItemKey: "tune-up",
    name: "Condenser coil cleaner",
    quantity: 2,
    unitCost: 12,
    unitPrice: 28,
  },
  {
    customerKey: "lakewood",
    jobKey: "completedLakewoodWater",
    serviceItemKey: "water-heater",
    name: "Upper thermostat — 4500W",
    quantity: 1,
    unitCost: 28,
    unitPrice: 95,
  },
  {
    customerKey: "marcus",
    jobKey: "completedMarcusNoCool",
    serviceItemKey: "refrigerant-leak",
    name: "R-410A refrigerant — 2 lb",
    quantity: 2,
    unitCost: 45,
    unitPrice: 85,
  },
  {
    customerKey: "sarah",
    jobKey: "completedSarahCap",
    serviceItemKey: "capacitor",
    name: "45/5 MFD run capacitor",
    quantity: 1,
    unitCost: 38,
    unitPrice: 275,
  },
  {
    customerKey: "ridgewood",
    jobKey: "completedRidgewoodBlower",
    serviceItemKey: "blower-motor",
    name: "ECM blower motor — 1/2 HP",
    quantity: 1,
    unitCost: 285,
    unitPrice: 685,
  },
  {
    customerKey: "bistro84",
    jobKey: "completedBistroRefrigerant",
    serviceItemKey: "refrigerant-leak",
    name: "Flare fitting repair kit",
    quantity: 1,
    unitCost: 22,
    unitPrice: 65,
  },
  {
    customerKey: "mainStreet",
    jobKey: "completedMainStreetThermostat",
    serviceItemKey: "thermostat-install",
    name: "Programmable thermostat",
    quantity: 1,
    unitCost: 85,
    unitPrice: 195,
  },
  {
    customerKey: "sunrise",
    jobKey: "completedSunriseMaint",
    serviceItemKey: "tune-up",
    name: "RTU belt set",
    quantity: 1,
    unitCost: 35,
    unitPrice: 78,
  },
  {
    customerKey: "westlake",
    jobKey: "completedWestlakeMaint",
    serviceItemKey: "tune-up",
    name: "MERV-13 filter — 20x25x4",
    quantity: 2,
    unitCost: 28,
    unitPrice: 55,
  },
  {
    customerKey: "techHub",
    jobKey: "completedTechHubNoCool",
    serviceItemKey: "diagnostic",
    name: "VRF communication board",
    quantity: 1,
    unitCost: 320,
    unitPrice: 580,
  },
];

export const HVAC_DEMO_ESTIMATES: EstimateSeed[] = [
  {
    key: "draftFurnace",
    customerKey: "emily",
    jobKey: "furnaceQuoteTomorrow",
    estimateNumber: "EST-DEMO-2001",
    status: "approved",
    subtotal: 4200,
    validUntilDaysFromNow: 21,
    notes: "Approved furnace replacement — installation scheduled after on-site measurement.",
    createdDaysAgo: 4,
    lineItems: [
      {
        serviceItemKey: "furnace-replacement",
        name: "Gas Furnace Replacement",
        description: "80% AFUE furnace replacement with startup and permit.",
        quantity: 1,
        unitPrice: 4200,
      },
    ],
  },
  {
    key: "sentMaintenance",
    customerKey: "james",
    estimateNumber: "EST-DEMO-2002",
    status: "approved",
    subtotal: 349,
    validUntilDaysFromNow: 10,
    notes: "Approved annual maintenance package — first visit booked.",
    createdDaysAgo: 12,
    lineItems: [
      {
        serviceItemKey: "maintenance-package",
        name: "Annual Maintenance Package",
        description: "Two seasonal tune-ups plus priority scheduling.",
        quantity: 1,
        unitPrice: 349,
      },
    ],
  },
  {
    key: "approvedRtu",
    customerKey: "greenfield",
    jobKey: "completedGreenfieldMaint",
    estimateNumber: "EST-DEMO-2003",
    status: "approved",
    subtotal: 7850,
    validUntilDaysFromNow: 30,
    notes: "Approved packaged RTU replacement — installation scheduled with permit pulled.",
    createdDaysAgo: 35,
    lineItems: [
      {
        serviceItemKey: "system-replacement",
        name: "Packaged RTU Replacement",
        description: "Remove existing rooftop unit and install new packaged system.",
        quantity: 1,
        unitPrice: 7850,
      },
    ],
  },
  {
    key: "draftDuctwork",
    customerKey: "mainStreet",
    estimateNumber: "EST-DEMO-2004",
    status: "approved",
    subtotal: 890,
    validUntilDaysFromNow: 14,
    notes: "Approved ductwork repair — scheduled with retail RTU maintenance visit.",
    createdDaysAgo: 2,
    lineItems: [
      {
        serviceItemKey: "ductwork-repair",
        name: "Ductwork Repair",
        description: "Seal and repair disconnected supply duct in ceiling plenum.",
        quantity: 1,
        unitPrice: 890,
      },
    ],
  },
  {
    key: "sentRtuRepair",
    customerKey: "bistro84",
    estimateNumber: "EST-DEMO-2005",
    status: "approved",
    subtotal: 1425,
    validUntilDaysFromNow: 21,
    notes: "Approved commercial RTU repair — parts ordered, install window confirmed.",
    createdDaysAgo: 5,
    lineItems: [
      {
        serviceItemKey: "rtu-repair",
        name: "Commercial RTU Repair",
        description: "Diagnose and repair rooftop packaged unit components.",
        quantity: 1,
        unitPrice: 475,
      },
      {
        serviceItemKey: "labor",
        name: "Standard Labor Rate",
        description: "Additional labor for compressor swap.",
        quantity: 10,
        unitPrice: 95,
      },
    ],
  },
  {
    key: "sentIaq",
    customerKey: "westlake",
    estimateNumber: "EST-DEMO-2006",
    status: "approved",
    subtotal: 1150,
    validUntilDaysFromNow: 30,
    notes: "Approved indoor air quality upgrade for medical office waiting room.",
    createdDaysAgo: 4,
    lineItems: [
      {
        serviceItemKey: "iaq-addon",
        name: "Indoor Air Quality Add-On",
        description: "UV light and MERV-13 media filter upgrade.",
        quantity: 1,
        unitPrice: 1150,
      },
    ],
  },
  {
    key: "approvedMaintPackage",
    customerKey: "sunrise",
    estimateNumber: "EST-DEMO-2007",
    status: "approved",
    subtotal: 698,
    validUntilDaysFromNow: 45,
    notes: "Approved annual maintenance package for both buildings.",
    createdDaysAgo: 40,
    lineItems: [
      {
        serviceItemKey: "maintenance-package",
        name: "Annual Maintenance Package",
        description: "Two seasonal tune-ups per building.",
        quantity: 2,
        unitPrice: 349,
      },
    ],
  },
  {
    key: "approvedBlower",
    customerKey: "ridgewood",
    jobKey: "completedRidgewoodBlower",
    estimateNumber: "EST-DEMO-2008",
    status: "approved",
    subtotal: 685,
    validUntilDaysFromNow: 60,
    notes: "Approved blower motor replacement for clubhouse unit.",
    createdDaysAgo: 42,
    lineItems: [
      {
        serviceItemKey: "blower-motor",
        name: "Blower Motor Replacement",
        description: "Replace failed ECM blower motor and verify airflow.",
        quantity: 1,
        unitPrice: 685,
      },
    ],
  },
  {
    key: "declinedReplacement",
    customerKey: "marcus",
    estimateNumber: "EST-DEMO-2009",
    status: "sent",
    subtotal: 6200,
    validUntilDaysFromNow: 14,
    notes: "Dual-zone system upgrade proposal — customer reviewing financing options.",
    createdDaysAgo: 4,
    lineItems: [
      {
        serviceItemKey: "system-replacement",
        name: "Packaged RTU Replacement",
        description: "Full dual-zone system replacement proposal.",
        quantity: 1,
        unitPrice: 6200,
      },
    ],
  },
  {
    key: "declinedOld",
    customerKey: "oakwood",
    estimateNumber: "EST-DEMO-2010",
    status: "approved",
    subtotal: 4200,
    validUntilDaysFromNow: 60,
    notes: "Approved central plant controls upgrade — phased install over two weekends.",
    createdDaysAgo: 45,
    lineItems: [
      {
        serviceItemKey: "furnace-replacement",
        name: "Boiler Component Upgrade",
        description: "Replace aging boiler controls and zone valves.",
        quantity: 1,
        unitPrice: 4200,
      },
    ],
  },
];

export const HVAC_DEMO_INVOICES: InvoiceSeed[] = [
  {
    key: "paidDiag",
    customerKey: "lakewood",
    jobKey: "completedLakewoodDiag",
    invoiceNumber: "INV-DEMO-3001",
    status: "paid",
    subtotal: 129,
    amountPaid: 0,
    issueDaysAgo: 24,
    dueDaysFromNow: 6,
    paidDaysAgo: 20,
    notes: "Diagnostic visit — paid in full.",
    lineItems: [
      {
        serviceItemKey: "diagnostic",
        name: "AC System Diagnostic",
        description: "Cooling diagnostic and airflow verification.",
        quantity: 1,
        unitPrice: 129,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 20,
        reference: "DEMO-PAY-3001",
        notes: "Paid in full — check.",
      },
    ],
  },
  {
    key: "partialMaint",
    customerKey: "greenfield",
    jobKey: "completedGreenfieldMaint",
    invoiceNumber: "INV-DEMO-3002",
    status: "partially_paid",
    subtotal: 1890,
    amountPaid: 1000,
    issueDaysAgo: 38,
    dueDaysFromNow: 12,
    notes: "Quarterly maintenance — deposit received, final balance on net-30 terms.",
    lineItems: [
      {
        serviceItemKey: "tune-up",
        name: "HVAC Seasonal Tune-Up",
        description: "Quarterly commercial maintenance service.",
        quantity: 10,
        unitPrice: 189,
      },
    ],
    payments: [
      {
        amount: 600,
        paymentDaysAgo: 35,
        reference: "DEMO-PAY-3002A",
        notes: "Initial deposit.",
      },
      {
        amount: 400,
        paymentDaysAgo: 8,
        reference: "DEMO-PAY-3002B",
        notes: "Second installment.",
      },
    ],
  },
  {
    key: "overdueFurnace",
    customerKey: "james",
    jobKey: "completedJamesMaint",
    invoiceNumber: "INV-DEMO-3003",
    status: "paid",
    subtotal: 165,
    amountPaid: 0,
    issueDaysAgo: 20,
    dueDaysFromNow: 6,
    paidDaysAgo: 16,
    notes: "Furnace maintenance completed — paid in full.",
    lineItems: [
      {
        serviceItemKey: "furnace",
        name: "Furnace Maintenance",
        description: "Annual furnace maintenance service.",
        quantity: 1,
        unitPrice: 165,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 16,
        reference: "DEMO-PAY-3003",
        notes: "Paid in full — card on file.",
      },
    ],
  },
  {
    key: "paidHistoricalCap",
    customerKey: "james",
    jobKey: "completedJamesCap",
    invoiceNumber: "INV-DEMO-3004",
    status: "paid",
    subtotal: 275,
    amountPaid: 0,
    issueDaysAgo: 54,
    dueDaysFromNow: -24,
    paidDaysAgo: 50,
    notes: "Capacitor replacement — paid in full.",
    lineItems: [
      {
        serviceItemKey: "capacitor",
        name: "Capacitor Replacement",
        description: "Replace failed run capacitor.",
        quantity: 1,
        unitPrice: 275,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 50,
        reference: "DEMO-PAY-3004",
        notes: "Historical paid invoice for revenue reporting.",
      },
    ],
  },
  {
    key: "paidMarcus",
    customerKey: "marcus",
    jobKey: "completedMarcusNoCool",
    invoiceNumber: "INV-DEMO-3005",
    status: "paid",
    subtotal: 520,
    amountPaid: 0,
    issueDaysAgo: 10,
    dueDaysFromNow: 20,
    paidDaysAgo: 7,
    notes: "Refrigerant leak repair — paid via card on-site.",
    lineItems: [
      {
        serviceItemKey: "refrigerant-leak",
        name: "Refrigerant Leak Repair",
        description: "Locate leak, repair line set, evacuate, and recharge.",
        quantity: 1,
        unitPrice: 520,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 7,
        reference: "DEMO-PAY-3005",
        notes: "Paid in full — card on-site.",
      },
    ],
  },
  {
    key: "partialBistro",
    customerKey: "bistro84",
    jobKey: "completedBistroRefrigerant",
    invoiceNumber: "INV-DEMO-3006",
    status: "partially_paid",
    subtotal: 520,
    amountPaid: 300,
    issueDaysAgo: 12,
    dueDaysFromNow: 18,
    notes: "Refrigerant repair — deposit received, final balance due on net-30 terms.",
    lineItems: [
      {
        serviceItemKey: "refrigerant-leak",
        name: "Refrigerant Leak Repair",
        description: "Kitchen make-up air unit leak repair.",
        quantity: 1,
        unitPrice: 520,
      },
    ],
    payments: [
      {
        amount: 300,
        paymentDaysAgo: 42,
        reference: "DEMO-PAY-3006",
        notes: "Partial payment — restaurant manager check.",
      },
    ],
  },
  {
    key: "overdueSunrise",
    customerKey: "sunrise",
    jobKey: "completedSunriseMaint",
    invoiceNumber: "INV-DEMO-3007",
    status: "paid",
    subtotal: 189,
    amountPaid: 0,
    issueDaysAgo: 28,
    dueDaysFromNow: 2,
    paidDaysAgo: 24,
    notes: "Quarterly RTU maintenance — paid via ACH.",
    lineItems: [
      {
        serviceItemKey: "tune-up",
        name: "HVAC Seasonal Tune-Up",
        description: "Quarterly RTU maintenance service.",
        quantity: 1,
        unitPrice: 189,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 24,
        reference: "DEMO-PAY-3007",
        notes: "Paid in full — ACH transfer.",
      },
    ],
  },
  {
    key: "sentSarah",
    customerKey: "sarah",
    jobKey: "completedSarahCap",
    invoiceNumber: "INV-DEMO-3008",
    status: "sent",
    subtotal: 275,
    amountPaid: 0,
    issueDaysAgo: 3,
    dueDaysFromNow: 27,
    notes: "Capacitor replacement — recently sent, awaiting payment.",
    lineItems: [
      {
        serviceItemKey: "capacitor",
        name: "Capacitor Replacement",
        description: "Replace failed run capacitor on outdoor condenser.",
        quantity: 1,
        unitPrice: 275,
      },
    ],
  },
  {
    key: "sentOakwood",
    customerKey: "oakwood",
    jobKey: "completedOakwoodDiag",
    invoiceNumber: "INV-DEMO-3009",
    status: "sent",
    subtotal: 129,
    amountPaid: 0,
    issueDaysAgo: 5,
    dueDaysFromNow: 25,
    notes: "Zone valve diagnostic — invoice sent to property management.",
    lineItems: [
      {
        serviceItemKey: "diagnostic",
        name: "AC System Diagnostic",
        description: "Central plant zone valve diagnostic.",
        quantity: 1,
        unitPrice: 129,
      },
    ],
  },
  {
    key: "paidWestlake",
    customerKey: "westlake",
    jobKey: "completedWestlakeMaint",
    invoiceNumber: "INV-DEMO-3010",
    status: "paid",
    subtotal: 189,
    amountPaid: 0,
    issueDaysAgo: 65,
    dueDaysFromNow: -35,
    paidDaysAgo: 60,
    notes: "Semi-annual medical office maintenance — paid via ACH.",
    lineItems: [
      {
        serviceItemKey: "tune-up",
        name: "HVAC Seasonal Tune-Up",
        description: "Semi-annual preventive maintenance.",
        quantity: 1,
        unitPrice: 189,
      },
    ],
    payments: [
      {
        amount: 0,
        paymentDaysAgo: 60,
        reference: "DEMO-PAY-3010",
        notes: "Paid via ACH — medical office billing.",
      },
    ],
  },
];

export const HVAC_DEMO_NOTIFICATIONS: NotificationSeed[] = [
  {
    type: "job_assigned",
    title: "Job assigned",
    message: "You were assigned JOB-DEMO-1001 — HVAC Maintenance for James Chen.",
    entityType: "job",
    jobKey: "maintenanceToday",
  },
  {
    type: "job_completed",
    title: "Job completed",
    message: "JOB-DEMO-1032 preventive maintenance completed at Lakewood Apartments.",
    entityType: "job",
    jobKey: "completedTodayLakewood",
  },
  {
    type: "invoice_paid",
    title: "Payment received",
    message: "INV-DEMO-3001 was paid in full.",
    entityType: "invoice",
    invoiceKey: "paidDiag",
  },
  {
    type: "job_completed",
    title: "Job completed",
    message: "JOB-DEMO-1037 capacitor replacement completed for James Chen.",
    entityType: "job",
    jobKey: "completedTodayJames",
  },
  {
    type: "invoice_paid",
    title: "Payment received",
    message: "INV-DEMO-3005 was paid in full.",
    entityType: "invoice",
    invoiceKey: "paidMarcus",
  },
  {
    type: "job_completed",
    title: "Job completed",
    message: "JOB-DEMO-1017 blower motor replacement completed at Ridgewood Estates.",
    entityType: "job",
    jobKey: "completedRidgewoodBlower",
  },
];

export const HVAC_DEMO_SEED_PACK = {
  serviceItems: DEMO_SERVICE_ITEMS,
  customers: DEMO_CUSTOMERS,
  leads: DEMO_LEADS,
  equipment: DEMO_EQUIPMENT,
  jobs: DEMO_JOBS,
  materials: HVAC_DEMO_MATERIALS,
  estimates: HVAC_DEMO_ESTIMATES,
  invoices: HVAC_DEMO_INVOICES,
  notifications: HVAC_DEMO_NOTIFICATIONS,
};
