-- Conversation with the Chief of Staff.
--
-- ==================== WHY THIS IS A QUEUE, NOT A CHAT API ====================
-- The Agent Platform runs laptop-side behind NAT. Altair OS cannot open a
-- connection to it — `lib/integrations/decision-transport.ts` in that repo
-- states it plainly: "that is not a workaround: it is the only direction that
-- exists". A browser message therefore cannot be handed to the Chief
-- synchronously, and any UI that appeared to do so would be lying about where
-- the answer came from.
--
-- So a question is DURABLY QUEUED here and the platform pulls it on its next
-- cycle, exactly as it already pulls human decisions (migration 142). The
-- answer is written back through the same authenticated bridge. The UI says
-- "queued" until it lands, because that is the truth.
--
-- ==================== THE CURSOR IS 142's, DELIBERATELY ====================
-- `seq bigserial` and "everything after the highest seq I applied" is the same
-- protocol the decision queue uses, for the same reasons: a re-poll is a
-- no-op, a lost response costs nothing, and there is no acknowledgement
-- handshake to get wrong. Answering is what marks a question handled; nothing
-- gates on an ack.
--
-- ==================== WHAT A MESSAGE IS NOT ====================
-- A queued question is not an instruction to publish, approve or spend. It is
-- text. Everything the Chief does in response still passes the permission
-- engine, the approval binding, the publish gate and the effect ledger on the
-- platform side. This table stores a conversation and nothing else.

create table if not exists public.agent_chief_messages (
  id uuid primary key default gen_random_uuid(),
  -- Monotonic delivery cursor for the platform's pull.
  seq bigserial not null,
  company_id uuid not null references public.companies (id) on delete cascade,

  -- Groups a back-and-forth. Generated by Altair OS; the platform echoes it.
  conversation_id uuid not null,

  -- Who is speaking. `user` turns are pulled and answered; `chief` turns are
  -- written by the platform and are never pulled again.
  role text not null,
  body text not null,

  -- Lifecycle of a USER turn. A chief turn is always 'answered' on arrival.
  --   queued    written by the browser, not yet pulled
  --   answered  the platform replied; `answered_at` is stamped
  --   failed    the platform tried and could not; `error_detail` says why
  status text not null default 'queued',

  -- One question per (company, key). The browser mints the key so a
  -- double-submitted form cannot become two questions to the Chief — the same
  -- idempotency posture migration 142 takes for decisions.
  request_key text not null,

  -- Altair OS is the only system here with authenticated humans, so the asker
  -- is recorded from the session rather than trusted from a payload.
  asked_by_user_id uuid references auth.users (id) on delete set null,
  asked_by_email text,

  -- The user turn this chief turn answers. Null on a user turn.
  in_reply_to uuid references public.agent_chief_messages (id) on delete cascade,

  answered_at timestamptz,
  error_detail text,
  created_at timestamptz not null default now(),

  constraint agent_chief_messages_key_unique
    unique (company_id, request_key),
  constraint agent_chief_messages_role_check
    check (role in ('user', 'chief')),
  constraint agent_chief_messages_status_check
    check (status in ('queued', 'answered', 'failed')),
  -- Bounded like every other operator-facing string in this schema. A model
  -- answer that ran away is truncated by the writer, not absorbed whole.
  constraint agent_chief_messages_body_len
    check (char_length(body) between 1 and 8000),
  constraint agent_chief_messages_error_len
    check (error_detail is null or char_length(error_detail) <= 1000),
  -- A chief turn always answers something; a user turn never does. Without
  -- this an answer could arrive detached from its question and the thread
  -- would have no defined order.
  constraint agent_chief_messages_reply_shape
    check (
      (role = 'chief' and in_reply_to is not null)
      or (role = 'user' and in_reply_to is null)
    ),
  -- An answered question has an instant; an unanswered one does not.
  constraint agent_chief_messages_answered_shape
    check ((status = 'answered') = (answered_at is not null))
);

-- The platform's work list: queued user turns, oldest first.
create index if not exists agent_chief_messages_pull_idx
  on public.agent_chief_messages (seq)
  where role = 'user' and status = 'queued';

-- The UI's read: one conversation, in order.
create index if not exists agent_chief_messages_conversation_idx
  on public.agent_chief_messages (company_id, conversation_id, created_at);

alter table public.agent_chief_messages enable row level security;

-- Posture (B), the ledger posture: operators read their own company's
-- conversation, the server writes. A browser never inserts here directly —
-- the Server Action does, after authenticating and checking the permission.
drop policy if exists "dispatchers can read chief messages"
  on public.agent_chief_messages;
create policy "dispatchers can read chief messages"
  on public.agent_chief_messages
  for select
  to authenticated
  using (
    public.is_active_company_member(company_id)
    and public.can_dispatch_jobs(company_id)
  );

grant select on table public.agent_chief_messages to authenticated;
revoke insert, update, delete on table public.agent_chief_messages from authenticated;
revoke all on table public.agent_chief_messages from anon;
grant all on table public.agent_chief_messages to service_role;

comment on table public.agent_chief_messages is
  'Conversation with the Chief of Staff. User turns are queued for the Agent Platform to pull (it is behind NAT and cannot be called); chief turns are written back through the authenticated agent bridge. Stores text only — every action the Chief takes still passes the platform''s own governance.';
